### ISSUE TITLE
Site upgrades

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#1]
series - under way, but perhaps something Ali could pick up as there is quite a lot of code there?
layout
chart
- [x] Create new d3fc/d3fc project to consolidate all components and contain site build + examples.
- [ ] Consistent eslint across all packages
- [ ] Auto-generate decent looking component pages from the relevant READMEs (enforcing more structure if necessary, but must be well documented/enforced)
- [ ] Refresh the style of the site
- [ ] Create dashboard

**Comment by ColinEberhardt** [comment]
How about listing our README markdown? I've noticed we deviate a little from the D3 style for documenting properties. It should be possible to enforce some of these conventions automatically.

Also, table of contents / links to sections within the markdown documentation - there has to be a better way of doing this than via the manual option!

**Comment by ColinEberhardt** [comment]
Regarding listing the README ... it's all too easy to end up with broken links:

https://github.com/d3/d3-shape/pull/75

**Comment by chrisprice** [comment]
Superseded by https://github.com/d3fc/d3fc/issues?q=is%3Aopen+is%3Aissue+label%3Asite
