### ISSUE TITLE
Some styles are not namespaced

### ISSUE THREAD

**Issue by stevenjob** [d3fc/d3fc#1009]
When using external svgs with d3fc, [styles from d3fc](https://github.com/ScottLogic/d3fc/blob/65a5f7e91f806dc8dc0ca5a93d6bf1c5b8c547d4/src/fc.css#L5-L14) are being erroneously applied.

It would be better if these selectors were namespaced to something more specific.

**Comment by PeterVermont** [comment]
Agree!

**Comment by chrisprice** [comment]
As noted in #1012, there should not be an empty `.chart` rule.

**Comment by ColinEberhardt** [comment]
we've removed all CSS from the project
