### ISSUE TITLE
Complete documentation?

### ISSUE THREAD

**Issue by JTorresConsulta** [d3fc/d3fc#1019]
Hi Scott. thank you very much for your work.

Have you a complete documentation of all functions with simple examples?
I dont understand some functions of your complete example scripts.

Thank you ! : )

**Comment by ColinEberhardt** [comment]
Hi @JTorresConsulta - you're in luck! We've just pushed a huge update that includes comprehensive documentation of all of the APIs. Take a look at the updated website.
