### ISSUE TITLE
Add CDN links for the packages

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#1023]
_From @ColinEberhardt on November 24, 2016 17:22_

Each of the API pages includes a link to github. I think it would also be really useful to add a link to the distribution build from the NPM CDN: unpkg.com

_Copied from original issue: d3fc/d3fc-temp#93_

**Comment by chrisprice** [comment]
Fixed by fd92519150dfb1279c54d91836ff29b18a54c330

**Comment by duhaime** [comment]
@chrisprice do you know what global is added to the window by the package on unpkg.com? 

My fiddle suggests d3fc is not defined :/ https://codepen.io/duhaime/pen/NWbaRLy

**Comment by duhaime** [comment]
Aha, it's `fc` :)
