### ISSUE TITLE
Example charts axes are mis-aligned 

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1036]
Looks like it is one pixel out:

![image](https://cloud.githubusercontent.com/assets/1098110/20893201/df43ee06-bb08-11e6-8336-bfee6706d887.png)

**Comment by chrisprice** [comment]
No more...
![image](https://user-images.githubusercontent.com/433457/44395584-3b801e00-a532-11e8-80d8-69fa4a011148.png)
