### ISSUE TITLE
Provide examples in ES-old syntax

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1052]
See the following:

https://github.com/d3fc/d3fc-sample/issues/34

I wonder whether our code snippets should be in both old, browser-ready syntax, as well as the one we have with arrows and imports.

(I can't remember which JS version is which these days!)

**Comment by chrisprice** [comment]
D3 opted for es5 syntax but that was almost a year ago. I don't like the
idea of our docs using it because I think it'll encourage patterns which
favour that syntax and it's going to be legacy very soon.

If we were using bleeding edge features of es2017 etc I'd feel differently!

**Comment by ColinEberhardt** [comment]
Fair point - and it looks like a significant proportion of people (~75%)  are transpiling these days:

http://stateofjs.com/2016/flavors/
