### ISSUE TITLE
Jumbled sentence on front page (Canvas / SVG blurb)

### ISSUE THREAD

**Issue by hollasch** [d3fc/d3fc#1058]
I'd gladly work up a PR, but can't figure out what this is trying to say: 

> With d3fc continues this pattern throughout our components, all of the d3fc-series components support both Canvas and SVG rendering.

This is on the front page, in the Canvas / SVG paragraph.

**Comment by chrisprice** [comment]
Good spot, thanks! Hopefully it now makes a bit more sense...
