### ISSUE TITLE
Are we bundling correctly?

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1060]
see the following:

https://github.com/rollup/rollup/wiki/pkg.module

> Tools such as rollup-plugin-node-resolve and Webpack 2 treat jsnext:main and module interchangeably

> pkg.module will point to a module that has ES2015 module syntax but otherwise only syntax features that node supports.

> Wait, it just means import and export – not other future JavaScript features?

**Comment by ColinEberhardt** [comment]
There is a very good discussion on jsnext:main and the newer package.module here:

https://github.com/jsforum/jsforum/issues/5

It does look like we should be transpiling the ES6 code to remove all ES6 features other than the import / export statements.

**Comment by chrisprice** [comment]
We chatted about this and I think the conclusion we came to was to remove
all of the non-standard package metadata until there's an established way
of doing things. Our usual tactic of copy d3 doesn't work because d3 is
authored in ES5.

**Comment by ColinEberhardt** [comment]
See also the discussion here

https://github.com/facebookincubator/create-react-app/issues/1125

**Comment by chrisprice** [comment]
Fixed by 8795bef6ee8bc95cdfcf4797474ec91cf55ea155
