### ISSUE TITLE
Crash while using with infamous

### ISSUE THREAD

**Issue by jibesh** [d3fc/d3fc#1068]
Hi,
I am trying to use d3fc (v11.0.0) along with infamous(v5.0.0) (https://github.com/trusktr/infamous). On including both of these libraries together, I am encountering an error message saying only one instance of babel-polyfill is allowed. 

In the following, I am presenting the code snippets denoting the order of inclusion of the libraries and the error message in each case.

```javascript
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/infamous/5.0.0/infamous.min.js"></script> 
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/d3fc/11.0.0/d3fc.bundle.min.js"></script> 
```
![image](https://cloud.githubusercontent.com/assets/1507011/24918106/7577fb62-1edf-11e7-9ea1-2071bb2ab67b.png)

or
```javascript
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/d3fc/11.0.0/d3fc.bundle.min.js"></script> 
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/infamous/5.0.0/infamous.min.js"></script> 
```
![image](https://cloud.githubusercontent.com/assets/1507011/24918249/0df0e17e-1ee0-11e7-8d89-2c0a8037dc7a.png)

**Comment by ColinEberhardt** [comment]
Thanks for pointing out this issue. I don't think either library should be including the babel-polyfill. It looks like `externalHelpers: false` should fix this:

https://github.com/rollup/rollup-plugin-babel#helpers

I'll have a go at resolving this shortly.

**Comment by ryanggrey** [comment]
I see that `v11` is being used. This included the distributions `d3fc.bundle.js` and `d3fc.js`. The `d3.bundle.js` distribution included `d3` and other libs such as `babel-polyfill` for ease of use but, as shown above, this introduces problems. 

`v12` does not include the `d3fc.bundle.js` distribution so this is no longer a problem. Those using `v11` can use the `d3fc.js` distribution to get around this problem (note that you will need to then include `d3` manually).

**Comment by ColinEberhardt** [comment]
Thanks for investigating @ryanggrey - as this only effects an older version, I'm closing this issue.

**Comment by trusktr** [comment]
Hello @jibesh although the latest version of d3fc doesn't use babel-polyfill anymore so you won't get the conflicts, I'm going to look at migrating infamous over to [Bublé](https://buble.surge.sh) which should result in leaner faster code, as well as no conflicts with other libraries. Thanks for pointing this out! I'll keep track of it in https://github.com/trusktr/infamous/issues/114 (sorry for the late reply!).

**Comment by trusktr** [comment]
@ColinEberhardt I've gone to a mix of Babel and Buble for transpile. I wonder if using `transform-runtime` would have same problem as using `babel-polyfill`?

**Comment by trusktr** [comment]
I think it won't, because now transpiled code has stuff like

```js
var _symbol = require('babel-runtime/core-js/symbol');

var _symbol2 = _interopRequireDefault(_symbol);
```

so there isn't global pollution like with `babel-polyfill`. I think this is a better approach, and achieves basically the same thing.
