### ISSUE TITLE
How to correctly render to canvas on retina displays?

### ISSUE THREAD

**Issue by ezekg** [d3fc/d3fc#1071]
Using this example, https://bl.ocks.org/ColinEberhardt/ab37d7973bfe32feea8cad21bd40fe1a.

### Canvas
![image](https://user-images.githubusercontent.com/6979737/28391003-dbfda836-6ca1-11e7-874c-c7809b01459d.png)

### SVG
![image](https://user-images.githubusercontent.com/6979737/28391011-e41e5e84-6ca1-11e7-81b0-51a638722da5.png)

As you can see, the canvas chart is rendering blurry on retina displays. Is there a way to fix this?

**Comment by chrisprice** [comment]
It looks like the canvas implementation should be making use of `devicePixelRatio` (https://github.com/d3fc/d3fc-element/issues/30) but that comes without it's own drawbacks so we'll probably have to make that opt-in behaviour. For now have you tried using the SVG version?

**Comment by ezekg** [comment]
Great. I'm using the SVG version for now but would like to use canvas when possible for performance reasons since I'm dealing with near real-time data. 👍

**Comment by chrisprice** [comment]
Closing as #1126 covers the required work to fix this issue
