### ISSUE TITLE
How to control annotation position

### ISSUE THREAD

**Issue by CoolM1234** [d3fc/d3fc#1080]
Hi,
I m using your yahoo financial chart.
By the fault, the position of annotation is set to right handle.And now, I wan to set to another position(not left handle), but I don't know how to get the particular data position. For example (cx =("d.date's position " )& cy =("d.close's position. Becuz I m trying to add a circle annotation.

**Comment by ColinEberhardt** [comment]
If you're referring to the charts in this blog post:

http://blog.scottlogic.com/2015/07/08/yahoo-finance-chart.html

I'm afraid the code is a little dated (using D3v3 and an older version of d3fc). I'm planning on updating that example ... when I can find the time!
