### ISSUE TITLE
trying to add labels to scatter chart via fc.seriesSvgMulti()

### ISSUE THREAD

**Issue by eesur** [d3fc/d3fc#1086]
I'm unable to add labels using [d3fc-label-layout](https://d3fc.io/api/label-layout-api.html) to a `fc.chartSvgCartesian` chart, I'm getting this error:

![screen shot 2017-10-12 at 14 32 16](https://user-images.githubusercontent.com/1597761/31498685-8baf4d52-af5a-11e7-9f78-0a1a8a5adb7a.png)

here's my code for the example: https://codepen.io/eesur/pen/LzBzXB

When I console out, I'm getting all the values as expected for the labels, apart form the applied `x` and `y` scale. Is it something to do with the delay in responsive render for the plotarea?

Sorry if I missing something obvious, I couldn't find an example using it with the `c.seriesSvgMulti()`,  and worked of the docs and the [map example](https://bl.ocks.org/ColinEberhardt/389c76c6a544af9f0cab) thanks for any help/guidance

**Comment by ColinEberhardt** [comment]
Hmmm .... I think we changed d3fc-label-layout in a way that makes it a bit harder to integrate with d3fc-series. With our D3v3 component the component exposed xScale / yScale properties:

https://github.com/d3fc/d3fc/blob/legacy/src/layout/label.js#L29

However, the v4 version does not.

@chrisprice do you have any recollection of why we removed these? the chart component expects anything added to the plot area to expose these properties.

**Comment by chrisprice** [comment]
As discussed offline, I think it was an omission. Happy to see `xScale/yScale` properties, which default to identity and are applied to the positions.

**Comment by ColinEberhardt** [comment]
@eesur this issue has now been fixed - you can see a complete worked example here:

https://bl.ocks.org/ColinEberhardt/27508a7c0832d6e8132a9d1d8aaf231c

hope that helps!

**Comment by eesur** [comment]
thanks Colin, you guys are awesome! 
much appreciated :)

**Comment by ColinEberhardt** [comment]
This issue shouldn't be closed until the label-layout release makes its way into d3fc. unfortunately semantic release failed on the merge commit https://github.com/d3fc/d3fc-label-layout/pull/29

**Comment by chrisprice** [comment]
The latest versions of all code should now be released
