### ISSUE TITLE
lineSeries fill and stroke decorators get reset on redraw (non-idempotent?)

### ISSUE THREAD

**Issue by eponymous301** [d3fc/d3fc#1088]
Similar code to #1087, this time drawing a line series instead of candlestick.

[Replication case (codepen)](https://codepen.io/eponymous/pen/PJyqdx)

Click on lower pane, hit left or right arrow key. The line series path element has fill reset to "none" and stroke to "#000", but the other decorator attrs (fill-opacity, stroke-opacity, stroke-width) are still ok.

Problem does not occur if seriesSvgLine is replaced instead with seriesSvgBar.

Setting div's innerHTML to '' before drawing chart also prevents issue, at cost of flicker.

**Comment by eponymous301** [comment]
I tried hacking the minified js, I believe I took out [these lines](https://github.com/d3fc/d3fc-series/blob/master/src/svg/line.js#L27-L28) and it seems to work around the issue (although now I have to explicitly set 'fill' to 'none' in my decorator).

**Comment by eponymous301** [comment]
seriesSvgArea seems to have a similar issue with fill getting reset to '#ddd' (perhaps from [this analogous line](https://github.com/d3fc/d3fc-series/blob/master/src/svg/area.js#L34))

**Comment by ColinEberhardt** [comment]
Well spotted, and yes, you've found the right lines - that code should only be executed within the enter selection. I should have time to release a fix today.
