### ISSUE TITLE
Documentation note - need to use !important for some attrs/elements but not others

### ISSUE THREAD

**Issue by eponymous301** [d3fc/d3fc#1091]
When I try to set some div.chart-label styles (e.g. line-height, text-align) via CSS it gets overridden unless I use !important. I was surprised since for other items (example: .candlestick.down) overriding defaults using CSS works fine without "!important".

[codepen](https://codepen.io/eponymous/pen/yzReBp)

I'm guessing that the differing behavior is due to HTML + CSS + SVG being a crufty layer cake, I see for candlestick case that <g> defines default 'fill' and 'stroke' via individual SVG attributes (which seem to have lower CSS precedence) whereas for div.chart-label that a single combined style string is used (out of necessity, since there are no corresponding individual element attributes).

Not a big deal since !important is available, but a note in the docs (or an example of how to set/override some of the various superficial cosmetic aspects of chart e.g. margins/line heights etc) would be helpful.

I was going to suggest a decorator like "omitDefaultStyles()" but looking at the source code this looks like it would complicate life too much due to interactions with flex / orientation / padding etc.

**Comment by chrisprice** [comment]
Those styles would need to be overridden using the decorate functionality e.g. -
```js
    chart.decorate(selection => {
      selection.enter()
         .select('.chart-label')
         .style('height', '5em')
         .style('line-height', '5em')
    });
```

**Comment by chrisprice** [comment]
Added to docs in 76c4bb1041d462fbae95c45772b61476c41d4163
