### ISSUE TITLE
plot-area adding multiple series and responsive when window is not changes

### ISSUE THREAD

**Issue by CoolM1234** [d3fc/d3fc#1093]
Hi~ 
I reference to this article: (http://blog.scottlogic.com/2017/01/10/efficient-svg-layout-with-d3.html)

Adding multiple series in plot-area
------------------
I am trying append ('g') to each series. But when i append('g') for each series the responsive is not working.
The following is my code:  
![capture](https://user-images.githubusercontent.com/30105375/32161331-1d667926-bd90-11e7-959b-1a506e0ebb3a.PNG)

Thanks~

**Comment by chrisprice** [comment]
Closing as there's not enough information to reproduce and this is an old issue. If it's still a problem please raise a new issue.
