### ISSUE TITLE
d3fc with threeJs

### ISSUE THREAD

**Issue by 3kynox** [d3fc/d3fc#1094]
Hello,

I have just a question, how do you think it can be complicated to integrate d3 / d3fc with threeJs ?

I see some interesting integrations and looks like WebGL render can handle more points than just canvas : 

https://www.nytimes.com/interactive/2015/03/19/upshot/3d-yield-curve-economic-growth.html

Thanks for any thoughts :)

**Comment by ColinEberhardt** [comment]
That's a pretty funky chart!

Integration of d3fc and threeJS should be quite straightforward. With D3 / d3fc the rendering logic is separate from the core 'charting' logic. You can see this in actions with d3fc-series where components exist for svg and canvas, with common  base components for each:

https://github.com/d3fc/d3fc-series/tree/master/src

I think this would be a good starting point for threeJS, by adding an series implementations.

**Comment by 3kynox** [comment]
This is clearly good news to have logic separated like you said. 

I'm new to the d3 world currently but I'm involved in a crypto-currencies project where I have to design charts with some various indicators. Your project will be the chosen one and why not having in the future a "3D button".

Thanks a lot for your very engaging informations.

See you later, closing here.
