### ISSUE TITLE
adding decoration screws up redraw/update

### ISSUE THREAD

**Issue by utdrmac** [d3fc/d3fc#1095]
Hello. I'm attempting to use d3fc to create some financial charts. My Bollinger bands, EMAs and SMA's are calculated by the app and the data is sent to webpage using socket.io every minute. When data arrives, I simply append/slice on to the existing array and call the renderChart function, extremely similar [to this example](https://bl.ocks.org/ColinEberhardt/ab7805a9a7af9717e86adc1656fa98d9).

The issue is when adding decoration to any of the line()s, or area()s, the redraw no longer "updates" the existing lines/areas and instead appends new ones.

This works perfectly:
```
const bbarea = fc.seriesSvgArea()
  .mainValue(function(d) { return d.upperBB; })
  .baseValue(function(d) { return d.lowerBB; })
  .crossValue(crossValue);
```

This does not and produces the screenshot below. In it, you can see, as new data arrives, it repeatedly adds new bollinger bands instead of "shifting" the existing one.

```
const bbarea = fc.seriesSvgArea()
  .mainValue(function(d) { return d.upperBB; })
  .baseValue(function(d) { return d.lowerBB; })
  .crossValue(crossValue)
  .decorate(function(s) {
    s.enter().attr("class", "data-line bbands-area")
  });
```

<img width="1084" alt="screen shot 2018-01-29 at 6 34 25 pm" src="https://user-images.githubusercontent.com/4413670/35541971-21a67bc8-0523-11e8-9a66-fa240bc4f229.png">

I simply want to assign a CSS class to the various areas and lines so they can be colorized correctly. I've been trying to follow the examples here: https://d3fc.io/introduction/decorate-pattern.html

Any ideas why adding this decorate function is making it so things get appended rather than updated?

**Comment by utdrmac** [comment]
So through some trial-and-error, seems there is an unwritten rule that whatever class you put through decorate, it must contain a class called the type of this object.

This worked. Notice the difference from above, I added the 'area' class.

```
const bbarea = fc.seriesSvgArea()
  .mainValue(function(d) { return d.upperBB; })
  .baseValue(function(d) { return d.lowerBB; })
  .crossValue(crossValue)
  .decorate(function(s) {
    s.enter().attr("class", "area data-line bband-area")
  });
```

Similarly, for seriesSvgLine(), I had to ensure a CSS class "line" existed.

Is this requirement documented somewhere? Does d3fc somehow "expect" certain CSS classes for data-binding?

**Comment by chrisprice** [comment]
As you guessed a core part of D3 is the data join concept, for it to work
you need to be able to unambiguously select the set of nodes of interest.

You're fix is valid and the approach we commonly use. Another approach
which doesn't require knowledge of the inner workings of the components is
to use classed instead (
https://github.com/d3/d3-selection/blob/master/README.md#selection_classed)
which augments rather than replaces classes.

**Comment by ColinEberhardt** [comment]
Thanks for digging in a bit deeper. What's happening here is that the `seriesSvgArea` is rendered using a D3 datajoin that has a `path.area` selection:

https://github.com/d3fc/d3fc-series/blob/master/src/svg/area.js#L14

The `area` CSS class is added to all the newly created `path` elements, and is necessary to ensure future datajoins correctly identify enter and update selections.

In your first version of the code, you set the class of these same elements to `data-line bbands-area`, which means the datajoin no longer works properly. A better option might be to use the `classed` method:

https://github.com/d3/d3-selection/blob/master/README.md#selection_classed

> Is this requirement documented somewhere?

I'm afraid not!

**Comment by ColinEberhardt** [comment]
@chrisprice looks like we responded at the same time - glad to see we are giving the same advice ;-)

**Comment by chrisprice** [comment]
Great minds.... 🙂
