### ISSUE TITLE
Most CSS is hardcoded in the 'style' making overrides difficult

### ISSUE THREAD

**Issue by utdrmac** [d3fc/d3fc#1096]
In using D3FC, I've discovered it's extremely difficult to use CSS to layout charts and such because much of the "style" of D3FC is hardcoded into the `<d3fc-svg>` tags. I can use `!important` in CSS but I've read that is "like killing the foxes hunting your chickens with a nuclear bomb".

I'd really like to see most, if not all, styling moved out of the tags and in to CSS. This follows the Bootstrap model.

**Comment by ColinEberhardt** [comment]
That's a fair point, and in previous versions of d3fc we shipped CSS separately. However, we are trying to follow D3 conventions as closely as possible. 

With D3v3 the axis component didn't have any styling, it also didn't ship with CSS.

https://github.com/d3/d3/blob/9cc9a875e636a1dcf36cc1e07bdf77e1ad6e2c74/src/svg/axis.js

Whereas in D3v4 styling was added - to reduce the amount of work required to render a simple axis:

https://github.com/d3/d3-axis/blob/master/src/axis.js#L65

A 'post selection' approach for styling, which is similar to our [decorate pattern](https://d3fc.io/introduction/decorate-pattern.html), was introduced:

https://bl.ocks.org/mbostock/3371592

It's a tricky problem, and to be honest, neither approach is ideal!

**Comment by chrisprice** [comment]
As part of #1091 we noted how to override these built-in styles.
