### ISSUE TITLE
Multi-series using cartesian vs. custom layout

### ISSUE THREAD

**Issue by sos0** [d3fc/d3fc#1097]
![image](https://user-images.githubusercontent.com/1973082/35944027-ee11a29e-0c0f-11e8-89cb-c5403e0a76e5.png)

After successfully being able to render a candlestick chart + volume + MACD series on a cartesian chart (where volume/MACD series was rendering but not seen due to single domain), I am in the middle of writing fresh code to display the multi series in a custom layout (since cartesian only supports single y-axis) like [this example](https://bl.ocks.org/ColinEberhardt/485ad09b7967e2a0f9bfe6e10192c26a).

Replicating the code from the example worked, but when using actual data retrieved from gdax API, I get the following error above. (I will also note here again that the data was rendering fine when using cartesian + multi from d3fc.) I would love some guidance into how to fix this error (and am open to any other feedback related to other issues regarding my code.)

[Here's a gist](https://gist.github.com/sos0/5f49e1e06473671cf46e80fe58dc40d9) of my full chart generation code.

**Comment by sos0** [comment]
So (not entirely sure but) it looks like autoBandwidth expects a specific data structure, but I'm providing an array of json data. Removing autoBandwidth from my code rendered the candlestick and volume series. How would I modify autoBandwidth to allow an array of json data? Maybe this could be related to [this issue](https://github.com/d3fc/d3fc-series/issues/54) in d3fc-series?

**Comment by chrisprice** [comment]
Sorry I'm struggling to spot the issue just looking through the code. Any chance you could create a block which demonstrates it running? http://blockbuilder.org/

**Comment by sos0** [comment]
It's a bit difficult for me to generate one because my files are modularized and uses ES6. But to summarize my issue (If my suspicions are correct,) `autoBandwidth` function does not work on data that's an array of json.

**Comment by chrisprice** [comment]
OK, I'm not aware of why that would make a difference. Will take another
look when I'm back from holiday

**Comment by sos0** [comment]
I can no longer reproduce the error, but I'm guessing now that my data wasn't fully initialized due to bad async handling. I'll close this issue now!
