### ISSUE TITLE
site build failed

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1106]
The most recent build resulted in the gh-pages branch being in a broken state https://travis-ci.org/d3fc/d3fc/builds/405426650?utm_source=github_status&utm_medium=notification

Looks like there was a problem here:

~~~
PARSING READMES
DONE PARSING READMES
FILTERING READMES
DONE FILTERING READMES
YAML-IFYING READMES
DONE YAML-IFYING READMES
[TypeError: this is not a typed array.]
~~~

It worked when building locally and I've pushed the site.

**Comment by ColinEberhardt** [comment]
Also d3 has changed the folder where the distribution builds are located. It was `d3/build/d3.min.js`, and is now `d3/dist/d3.min.js`

**Comment by chrisprice** [comment]
For a long time I've been meaning to adopt a monorepo, as part of investigating this issue I've found a number of other issues and so I've taken the plunge and moved us over. I'm sure there are some issues remaining but the site now builds successfully and a number of the packaging issues we were having should now be resolved.
