### ISSUE TITLE
Collated feedback from beta review

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#111]
- [x] Documentation tab should not be highlighted on the 404 page
- [x] Cartesian should be capitalised
- [x] Broken codepen link on https://beta.d3fc.io/examples/streaming/index.html due to lack of jQuery
- [x] The 'raise issue' link styling on the 404 page is not correct
- [x] Add links to 'edit documentation' to make it easier for people to contribute small fixes.
- [x] Issues with parsing markdown links that contain titles - as per [this comment](https://github.com/d3fc/d3fc/issues/111#issuecomment-263357671) below.
- [x] There is no content under this heading https://beta.d3fc.io/api/element-api.html#d3fc-svg
- [x] The footer on this page is inconsistent https://beta.d3fc.io/api/scripts-api.html
- [x] 'Installing' sections are removed, but not 'installation' as per [this comment](https://github.com/d3fc/d3fc/issues/111#issuecomment-263386919)

**Comment by jleft** [comment]
Images have title text trailing on [d3fc-technical-indicator API page](https://beta.d3fc.io/api/technical-indicator-api.html):

![technical-indicator-title-text](https://cloud.githubusercontent.com/assets/2017615/20680676/edf826f4-b597-11e6-96ac-b108841f6e73.PNG)

**Comment by jleft** [comment]
It looks like the `installing` sections are [removed, by the site builder](https://github.com/d3fc/d3fc/blob/master/site/builder/filterReadmes.js#L37), from the API docs, but d3fc-annotation, d3fc-element and d3fc-group have _Installation_ sections, not _Installing_ sections, which are not removed.
