### ISSUE TITLE
Symbol.iterator is not defined on Android and older iOS

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1114]
_From @lukerayman on January 9, 2018 15:5_

I work on React Native app for iOS and Android using Expo SDK (0.22). I use `modeMedian` from `d3fc-sample` to downsample data and it works correctly only on iOS. On Android I'm getting this error:

```
undefined is not a function (evaluating 'names[typeof Symbol === 'function' ? Symbol.iterator : '@@iterator']()')
```

The error occurs in `d3fc-rebind/build/d3fc-rebind.js` file. To fix it in my project locally, I replaced this code:
```js
for (var _iterator = names[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
    var name = _step.value;
    target[name] = createReboundMethod(target, source, name);
}

```
with this:
```js
for (var i = 0; i < names.length; i += 1) {
    var name = names[i];
    target[name] = createReboundMethod(target, source, name);
}
```

It looks like there is a problem with using `Symbol.iterator` in React Native apps.

_Copied from original issue: d3fc/d3fc-sample#43_

**Comment by ColinEberhardt** [comment]
It's cool to hear that you are using this within a React Native app. For a bit of context, the d3fc-* packages are generally consumed via the top-level `d3fc` package, which documents their environment requirements.

From the [getting started guide](https://d3fc.io/introduction/getting-started.html):

> d3fc supports modern browsers. For pre-Edge versions of IE, you'll need a couple of polyfills in order to run d3fc code within the browser. The first is a polyfill for `Symbol`, such as [es6-symbol](https://github.com/medikoo/es6-symbol), or the general [babel-polyfill](https://www.npmjs.com/package/babel-polyfill), and the second is a polyfill for `CustomEvent`, such as [custom-event-polyfill](https://github.com/krambuhl/custom-event-polyfill).

It sounds like the Android JavaScript environment doesn't support `Symbol`, how about trying the [es6-symbol](https://github.com/medikoo/es6-symbol) polyfill?

**Comment by ColinEberhardt** [comment]
_From @lukerayman on January 15, 2018 11:53_

I tried `es6-symbol` but it didn't help.

**Comment by chrisprice** [comment]
From a quick google around, this [appears to be an issue](https://github.com/apollographql/graphql-tools/issues/535#issuecomment-362941047) with react-native's Android JS engine and existing polyfills that they are using. As Symbol is a well defined part of JS, this is definitely a bug on their side.
