### ISSUE TITLE
Indenting between the candles

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1121]
_From @dormadekhin-denis on June 22, 2018 5:4_

How can I add indents between candles for seriesSvgCandlestick?

_Copied from original issue: d3fc/d3fc-series#58_

**Comment by ColinEberhardt** [comment]
What do you mean by indents? Can you provide a picture that illustrates?

**Comment by ColinEberhardt** [comment]
_From @dormadekhin-denis on June 22, 2018 8:34_

![image](https://user-images.githubusercontent.com/32381310/41766620-b40121a6-7631-11e8-8b32-a475353fe421.png)

**Comment by chrisprice** [comment]
Setting the [bandwidth](https://d3fc.io/api/series-api.html#auto-bandwidth) of the series or adjusting the auto bandwidth percentage should allow what you're after.
