### ISSUE TITLE
Allow auto-resize on surfaces

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1123]
_From @chrisprice on September 22, 2016 15:52_

Possible enhancement to allow `auto-resize` to be applied to `d3fc-svg` & `d3fc-canvas`. 

Workaround is to wrap the element in a `d3fc-group`.

_Copied from original issue: d3fc/d3fc-element#2_

**Comment by ColinEberhardt** [comment]
_From @chrisprice on October 19, 2016 13:3_

Pending feedback from users.

**Comment by chrisprice** [comment]
As we've not had any feedback I assume this isn't required
