### ISSUE TITLE
Allow the travis.yml checks to be disabled

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1130]
_From @ColinEberhardt on November 23, 2016 8:14_

In the d3fc/d3fc project we need a different travis.yml file, however the there checks are still quite relevant. see: https://github.com/d3fc/d3fc/pull/75

_Copied from original issue: d3fc/d3fc-scripts#44_

**Comment by chrisprice** [comment]
Only the one travis.yml file now
