### ISSUE TITLE
babel-preset-es2015 -> babel-preset-env

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1132]
_From @ColinEberhardt on October 16, 2017 8:45_

Currently generates a warning on install:

> We’re super 😸 excited that you’re trying to use ES2015 syntax, but instead of continuing yearly presets, the team recommends using babel-preset-env. By default, it has the same behavior as previous presets to compile ES2015+ to ES5. Please check out the readme for more info

http://babeljs.io/env

_Copied from original issue: d3fc/d3fc-scripts#119_

**Comment by chrisprice** [comment]
Already in use
