### ISSUE TITLE
NS_ERROR_FAILURE:  with getBBox()

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1134]
_From @Shadowman4205 on April 10, 2017 14:13_

I am getting this error with firefox, any workaround for this?

_Copied from original issue: d3fc/d3fc-label-layout#28_

**Comment by ColinEberhardt** [comment]
Hi @Shadowman4205 thanks for raising this issue. I tested the demo page (http://d3fc.github.io/d3fc-label-layout/) on the latest firefox (v52) and didn't see this issue.

Can you please provide further details on how to reproduce?

**Comment by chrisprice** [comment]
Closing as no response
