### ISSUE TITLE
Create a chart that supports multiple axes

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1150]
_From @ColinEberhardt on August 16, 2017 21:22_

It would be useful to be able to create a multi-axis chart ... needs a bit of design work. Need to think about ...

 - how to support left / right  top / bottom axes
 - support charts where the axes are visually separate, or are rendered within he same area of the chart.
 - how to rebind properties from multiple axes
 - whether to compromise or restrict the API in some way

_Copied from original issue: d3fc/d3fc-chart#31_

**Comment by ColinEberhardt** [comment]
_From @sos0 on February 7, 2018 5:24_

So is it safe to assume that currently this doesn't support multiple axes?

**Comment by ColinEberhardt** [comment]
Correct - it does not support multiple axes. Although you can create your own multi-axis chart, by looking at the way d3fc-chart is assembled.

**Comment by chrisprice** [comment]
See also #1017

**Comment by ColinEberhardt** [comment]
We don't need any more than the example here https://github.com/d3fc/d3fc/tree/master/packages/d3fc-chart#adding-a-second-axis
