### ISSUE TITLE
Support rendering of labels in between ticks

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1153]
_From @ColinEberhardt on April 4, 2017 14:13_

d3-axis doesn't support this, and it seems to be a popular request:

http://stackoverflow.com/questions/17544546/d3-js-align-text-labels-between-ticks-on-the-axis

_Copied from original issue: d3fc/d3fc-axis#14_

**Comment by chrisprice** [comment]
Duplicate of #541
