### ISSUE TITLE
Canvas equivalents?

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1160]
_From @chrisprice on August 18, 2016 14:51_

Currently all components are implemented as SVG only components.

_Copied from original issue: d3fc/d3fc-annotation#2_

**Comment by ColinEberhardt** [comment]
_From @ezekg on August 2, 2017 18:19_

What's the status on this? Anything I can do to help out?

**Comment by ColinEberhardt** [comment]
The status is pretty simple, we have't got around to it yet!

> Anything I can do to help out?

Any help would be appreciated. If you just want to try your hand at implementing one of the annotation types that would be great. The canvas implementations within d3fc-series might provide some good patterns to follow.

**Comment by ColinEberhardt** [comment]
_From @utdrmac on January 24, 2018 3:6_

@ColinEberhardt is this still work in progress? I just spent hours designing my app using fc.seriesCanvas* only to get black-flagged on the last lap?

**Comment by ColinEberhardt** [comment]
Hi @utdrmac good point, this has been on the 'to do' list for a little too long. I'll see if I can get this moving. Just out of interest, which specific annotations are you using?

**Comment by ColinEberhardt** [comment]
_From @utdrmac on January 24, 2018 16:37_

gridlines, x/y axis, crosshairs. financial-style app using CanvasCandlesticks().

**Comment by ColinEberhardt** [comment]
_From @ezekg on January 24, 2018 16:44_

Sorry I never got to contributing to this issue. I ended up drawing my annotations manually using the native canvas API, due to time constraints.

**Comment by Ro4052** [comment]
When writing a canvas implementation for the crosshair annotation, I've noticed a fundemental difference with `decorate` for the canvas version. The only way to achieve the same flexibility as the SVG version would be to have a `decorate` function for each line and one for the point. Would @chrisprice or @ColinEberhardt have any opposition to something like this? The current idea would be to have `xDecorate` for the vertical line, `yDecorate` for the horizontal line and `decorate` for the point. I'll move forward with this approach unless anyone has any objections.
