### ISSUE TITLE
Should we be merging enter and update

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1163]
_From @ColinEberhardt on September 27, 2016 5:24_

See: https://github.com/d3fc/d3fc-data-join/blob/master/src/dataJoin.js#L40

This makes migration of old d3fc components easier, but is it the correct thing to do? It threw me a little when updating d3fc-axis because my mind was thinking along the lines of D3v4 data joins, where the two are not merged automatically.

_Copied from original issue: d3fc/d3fc-data-join#22_

**Comment by ColinEberhardt** [comment]
_From @chrisprice on September 27, 2016 6:50_

Not sure. We already break the convention by appending to the enter
selection (which is required for decorate and is generally what you want).

**Comment by ColinEberhardt** [comment]
There is a good reason for that append, but I'm not sure there is one for performing the merge. Users can always perform the merge within their decorate function if they want to.

This will of course mean quite a bit of work to fix our existing components if we make this change ...

**Comment by ColinEberhardt** [comment]
_From @chrisprice on September 27, 2016 7:51_

I don't like that we've broken the convention but I'm concerned about how
much work it'll be to update. Maybe we go for a beta as is?

**Comment by ColinEberhardt** [comment]
> Maybe we go for a beta as is?

👍 - the impact on external users of not making this change is pretty minor. We can then assess the impact on _our_ code at a later date!

**Comment by chrisprice** [comment]
Closing for lack of comments

**Comment by chrisprice** [comment]
It could be argued that #1087 was caused by this
