### ISSUE TITLE
Axis with skipped weekends doesn't have any ticks

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1167]
When updating teh examples to v14 as per https://github.com/d3fc/d3fc/issues/1109 - the following example shows a regression:

http://blockbuilder.org/ColinEberhardt/0a5cc7ca6c256dcd6ef1e2e7ffa468d4

When weekends are skipped, no tick marks are rendered

**Comment by chrisprice** [comment]
So this [commit](https://github.com/d3fc/d3fc/commit/d8062b0e56e4fa3036ed3819bb94228d7abe60dd#diff-3953acd00e77a16487a3b95613dc3d2c) explicitly adds this behaviour. I'm not sure what the behaviour should be?

**Comment by chrisprice** [comment]
After a bit of research, I think it makes sense to push the decision on to the user. I can think of a number of different ways in which a user would want the replacement ticks to be selected (e.g. consistent pixel spacing, consistent domain spacing, domain specific spacing, etc.) so I don't think there's a sensible default.

A user can choose which ticks are displayed with something like -

```js
// ...

const xTickFilter = d3.timeDay.filter((d) => d.getDay() === 1);

// Create the gridlines and series
const gridlines = fc.annotationSvgGridline()
	.xTicks(xTickFilter);

// ...

// adapt the d3 time scale in a discontinuous scale that skips weekends
const skipWeekendScale = fc.scaleDiscontinuous(d3.scaleTime())
  .discontinuityProvider(fc.discontinuitySkipWeekends());

function renderChart() {
  // create a chart
  const chart = fc.chartSvgCartesian(
      checkbox.checked ? skipWeekendScale : d3.scaleTime(),
      d3.scaleLinear()
    )
    .xDomain(xExtent(data))
    .xTicks(xTickFilter)
    .yDomain(yExtent(data))
    .plotArea(multi);

  // ...
}

// ...
```

**Comment by chrisprice** [comment]
@ColinEberhardt as I can't edit the block, can you update with the above code and add this to the end of the description -

> N.B. By default, the automatic tick positioning of the scale will try to place the ticks on Sunday's at midnight. Unfortunately this they will be filtered out by the discontinuous scale because the ticks fall within the discontinuities. To work around this you can manually specify the tick interval using d3-time -

```
const xTickFilter = d3.timeDay.filter((d) => d.getDay() === 1);
gridlines.xTicks(xTickFilter);
chart.xTicks(xTickFilter);
```

**Comment by ColinEberhardt** [comment]
Thanks @chrisprice - I've updated the example
