### ISSUE TITLE
Materialise bl.ock examples locally

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#1188]
It would be really useful to have a consistent presentation of our examples. We currently have a few different ways of doing it -

* `packages/*/examples`
* `packages/*/site`
* `packages/d3fc-site/src/examples`
* bl.ock examples (listed at `packages/d3fc-site/src/examples/index.md`)

The bl.ock builder examples work really well for quickly creating an example and sharing it without having to spin up the project. However, they are quite painful to upgrade and it's hard to use them as a test suite to see the effect of a change locally before releasing a new version.

I would like to see a script of some form that is able to materialise the bl.ock examples locally. The local versions should be wired up to my local bundle rather than a released version. This should allow me to easily see the impact of my local changes to the project by reviewing the examples.

**Comment by ColinEberhardt** [comment]
We no longer use these
