### ISSUE TITLE
Links to edit this page are broken

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#1190]
E.g. https://d3fc.io/api/data-join-api.html

Found a problem in this page? [Submit a fix!](https://github.com/d3fc/d3fc-data-join/blob/master/README.md)

**Comment by dbarkey-scottlogic** [comment]
Please also fix the "View on GitHub" link. They currently reference the root rather than the package.

**Comment by andy-lee-eng** [comment]
"Submit a fix" links have been fixed - #1243
"View on Github" links are also mentioned here - #1244
