### ISSUE TITLE
How to draw a graph without any axes?

### ISSUE THREAD

**Issue by Tarang** [d3fc/d3fc#1198]
I'm following the d3 chart example here: https://bl.ocks.org/ColinEberhardt/7069875cf9c028b4d824c6a7b8ad8142

```
const candlestickSeries = fc.seriesSvgCandlestick()
      .bandwidth(2);

    // adapt the d3 time scale to add discontinuities, so that weekends are removed
    const xScale = fc.scaleDiscontinuous(d3.scaleTime())
      .discontinuityProvider(fc.discontinuitySkipWeekends());

    const chart = fc.chartSvgCartesian(
        xScale,
        d3.scaleLinear()
      )
      .plotArea(candlestickSeries);

    // use the extent component to determine the x and y domain
    const xExtent = fc.extentDate()
      .accessors([d => d.date]);

    const yExtent = fc.extentLinear()
      .accessors([d => d.high, d => d.low]);

    const parseDate = d3.timeParse("%d-%b-%y");

    let data = await d3.csv('assets/data.csv',
      // transform the data to use the default candlestick series properties
      row => ({
        open: row.Open,
        close: row.Close,
        high: row.High,
        low: row.Low,
        date: parseDate(row.Date)
    }))

    // set the domain based on the data
    chart.xDomain(xExtent(data))
      .yDomain(yExtent(data))

    // select and render
    d3.select('#chart-element')
      .datum(data)
      .call(chart);
```

How would I get rid of the axes (prevent them from drawing to begin with). I've tried multiple things, but removing them with css (display: none) seems to break the whole chart. Is there a setting to remove both axes?

**Comment by chrisprice** [comment]
The axis elements are measured to produce the domain for the scales which
are in turn used for the plot area series. Setting display none would
return zeros for these measurements, breaking the scale and therefore the
series.

One way to fix this would be to hide them using visibility hidden instead.
This means the axis elements are still layed out by the browser and given
valid measurements.

**Comment by chrisprice** [comment]
Alternatively you might be better off skipping d3fc-chart and dropping down a layer. Use d3fc-element to give you a rendering surface (with measurements), feed these into standard d3 x/y scales (using the surface measurements to set the range) and then pass these into whichever d3fc-series makes sense for your use case.

Closing for now, feel free to comment if you want to clarify anything.
