### ISSUE TITLE
Quandl data feed no longer maintained

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#1202]
From https://www.quandl.com/databases/WIKIP/documentation/about -

> As of April 11, 2018 this data feed is no longer actively supported by the Quandl community. We will continue to host this data feed on Quandl, but we do not recommend using it for investment or analysis.

**Comment by cprice-scottlogic** [comment]
Remove it from d3fc

**Comment by chrisprice** [comment]
We could look to replace it with something like the IEX feed but they're in the processing of switching their API versions. One to revisit in the future.

![image](https://user-images.githubusercontent.com/433457/50896674-afe42c80-1401-11e9-9215-37fe413d6dc2.png)
