### ISSUE TITLE
Axis question

### ISSUE THREAD

**Issue by serzhiio** [d3fc/d3fc#1206]
There are some examples of **Axis** function on [this](https://d3fc.io/api/axis-api.html) page.
But there are no examples on how to integrate it with resulting d3fc chart/multi/cartesian.
Could i see some examples of full implementation?

**Comment by serzhiio** [comment]
Looks like Cartesian chart supports only XY axes and cant handle more.

**Comment by ColinEberhardt** [comment]
The chart exposes `xDecorate` and `yDecorate` properties that allow you to decorate each axis. You can see an example of this here:

https://d3fc.io/api/chart-api.html#translating-the-y-axis

Yes, you are correct, cartesian on has a single X & Y axis, but it is fairly easy to add additional axes:

https://d3fc.io/api/chart-api.html#adding-a-second-axis

**Comment by serzhiio** [comment]
Thx for reply!
...but how to link some new data with new axis then? and how to add new **canvas** bars related to new axis?
There is a lack of info on this topic.

**Comment by serzhiio** [comment]
I'm trying to do this, but with no luck:
```
        chart = fc.chartCartesian(xScale, yScale)
          .yDomain(yExtent(newData))
          .xDomain(xExtent(newData))
          .svgPlotArea(gridlines)
          .canvasPlotArea(multi)
          .xTicks(7)
          .decorate(selection => {
            selection.enter()
              .append('d3fc-svg')
              .classed('v-axis', true)
              .classed('left-axis', true)
              .on('measure', () => {
                vScale.range([d3.event.detail.height, d3.event.detail.height * 2 / 3])
              })
              .on('draw', (d, i, nodes) => {
                d3.select(nodes[i]).select('svg').call(vAxis)
              })
              selection.select('d3fc-canvas')
              .on('draw', (d, i, nodes) => {
                const canvas = d3.select(nodes[i]).select('canvas').node().getContext('2d')
                const volumeBars = fc.seriesCanvasBar().crossValue(d => d[0]).mainValue(d => d[3]).context(canvas).xScale(xScale).yScale(vScale)
                volumeBars([d])
              })
          })
```

**Comment by chrisprice** [comment]
From a quick look that should work. Maybe you could create a codepen.io example showing it not working so we can debug it?

**Comment by serzhiio** [comment]
I've figired out all problems. Just made chart without Cartesian module.

**Comment by stereokai** [comment]
@serzhiio I know this was a long time ago, but any chance you can share that code? Thanks!
