### ISSUE TITLE
SCRIPT5022: d3fc-element depends on Custom Elements (v1). Make sure that you load a polyfill in older browsers.

### ISSUE THREAD

**Issue by serzhiio** [d3fc/d3fc#1207]
What could it be?

**Comment by serzhiio** [comment]
Okay, i've managed that:
  import '@babel/polyfill'
  import 'custom-event-polyfill'
  import 'document-register-element'

**Comment by edum18** [comment]
> Okay, i've managed that:
> import '@babel/polyfill'
> import 'custom-event-polyfill'
> import 'document-register-element'

@serzhiio I'm having the same problem. Can you provide more details? How did you install both? Did you import them on nuxt?
