### ISSUE TITLE
seriesSvgArea returns path instead group for decoration

### ISSUE THREAD

**Issue by NCarson** [d3fc/d3fc#1215]
This is the line from area.js:
```javascript
base.decorate()(path, data, index);
```
I think this should be:
```javascript
base.decorate()(g, data, index);
```
where g is the group selection and is how the other components I looked at behave. As it is, I cannot select the parent group element very easily or at least have not found a workaround. So I cannot do things such as append text labels to the area.

**Comment by NCarson** [comment]
I see that seriesSvgLine also returns the path instead of the group. Everything else returns the group from the svg series components.

**Comment by chrisprice** [comment]
I think this is probably just an oversight as I don't think we've ever had
cause to decorate additional elements onto an area. It's more typical we'd
do that on series utilising an element per datum e.g. bar. I can see that
it could be useful though and I don't think it should be treated
differently to area.

I can't think of a reason not to make this change (although it would be a
breaking change). I'll stick it in the backlog or would happily approve a PR

**Comment by chrisprice** [comment]
Sorry, shouldn't try to comprehend things so early in the morning! If you
re-arrange the words, it still kind of makes sense :)

I don't think we've ever had cause to decorate additional elements onto an
area/line series. It's more typical we'd do that on series utilising an
element per datum e.g. bar. Area/line series make use of a single path
element. Any chance you could explain what you're trying to achieve?

The immediate workaround I can think of is to do something like
d3.select(path.node().parentNode) in the decorate functions if you need
access to the path's container but that won't allow you to label individual
data points.

**Comment by chrisprice** [comment]
Closing for now, feel free to comment if you are still looking for a solution.
