### ISSUE TITLE
seriesCanvasPoint implementation of size function different to svg

### ISSUE THREAD

**Issue by Ro4052** [d3fc/d3fc#1233]
There is a difference in the implementation of the `size` function between `seriesCanvasPoint` and `seriesSvgPoint`. When calling `size` in the SVG version, the function is provided individual data points, i.e. `symbol(d, i)`. In the canvas case, the function is called as `symbol(data)`, meaning the whole data array is passed. In our case, we want the point size based off individual data points and so the SVG implementation works, but not the canvas one.

**Comment by ColinEberhardt** [comment]
Thanks @Ro4052 that sounds very much like a bug! Would you be up for creating a fix?

**Comment by Ro4052** [comment]
That's fine, we have a fix, I'm just looking at making an example for it.
