### ISSUE TITLE
d3fc vs D3FC

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1241]
OK, this is a minor point - but we have decided to call ourselves d3fc, however, more often than not people call our library D3FC.

Perhaps we should just change to all caps?

**Comment by Ro4052** [comment]
I think the reason I made that mistake was because of the logo on the main page:

![image](https://user-images.githubusercontent.com/29425751/54608823-8242e180-4a49-11e9-9378-2316f13a350a.png)
