### ISSUE TITLE
Discussion about chartCartesian

### ISSUE THREAD

**Issue by Ro4052** [d3fc/d3fc#1262]
#### Styling Differences

 - [x] check that with cartesian charts it is still relatively easy to rotate a y axis label vertically.
 - [x] migrate the various package / dev examples to `chartCartesian`
 - [x] migrate the website examples to `chartCartesian`
 - [x] migrate the various D3 blocks examples to `chartCartesian`
 - [x] re-add the chart label (based on creating examples) - see related issue comment https://github.com/d3fc/d3fc/issues/1259#issuecomment-490574556
 - [x] check whether we can solve much of the above by capitalising on CSS grid, if so, can we just add a few examples?

#### Canvas plot area issues

 - [x] adopt the approach of defaulting the canvas / svg plot area components to `null`.
 - [x] double check that a chart without any canvas / svg series still renders OK
 - [x] ensure we add these components via a data-join, not just the enter selection
 - [x] move the canvas to the back?
 - [ ] enhance the cartesian chart docs, we really need to illustrate some more of the common use cases

There are couple of points that @DevAndyLee and I believe are worth discussing about the implementation of the `chartCartesian` component. The first point regards styling differences between `chartCartesian` and the legacy components and the second concerns the canvas plot area still being present in a purely SVG chart.

### Styling Differences

The legacy components use `cartesianBase` which has a fair amout of code that is not applied to the charts produced by `chartCartesian`. This seems to be mostly styling that is handled in css but there is one more noticeable difference in that the legacy components rotate the y labels. This means they are parallel to the y axis and take up less space, the same is not applied to `chartCartesian`.

### Canvas Plot Area

This issue is a little trickier. In many cases, users will want to draw a chart using only SVG. One of the benefits of SVG is that it is very easy to interact with. However, with `chartCartesian`, a canvas plot area is placed over the top, meaning it must be hidden/removed by the user in order to interact with the SVG plot. This isn't necessarily a huge issue but is less obvious with the legacy `chartSvgCartesian` and `chartCanvasCartesian` components. As the user specifies what plot area they want, it would be reasonable to expect that the other plot area would be hidden/removed automatically.

Although this issue would be relatively easy to resolve in the above case, these are legacy components and so may be less relevant. One simple solution for `chartCartesian` is to set the initial values for `canvasPlotArea` and `svgPlotArea` to  `null`, instead of `multi` components. This way, it would be easy to see which plot areas aren't being used and hide them. However, as Andy realised, the fact that `canvasPlotArea` and `svgPlotArea` are getters that can then have their properties changed, this could be a breaking change is a user alters the initial `multi` object rather than providing their own.

Another, non-breaking, solution would be to use boolean values to track whether the setters for `canvasPlotArea` and `svgPlotArea` have been called. If they have, they need to be drawn. Otherwise, it would be necessary to see if the `series` value has changed to determine whether the plot area can be hidden. This would be a less attractive solution but should not break any current usage of the component.

**Comment by ColinEberhardt** [comment]
_moved to top of issue_

**Comment by ColinEberhardt** [comment]
_moved to top of issue_

**Comment by Ro4052** [comment]
> ## Styling Differences
> * [x]  check that with cartesian charts it is still relatively easy to rotate a y axis label vertically.
> * [x]  migrate our current examples to `chartCartesian`
> * [x]  consider re-adding the chart label (based on creating examples) - see related issue comment [#1259 (comment)](https://github.com/d3fc/d3fc/issues/1259#issuecomment-490574556)
> * [x]  check whether we can solve much of the above by capitalising on CSS grid, if so, can we just add a few examples?

* #1266 Migrates examples to `chartCartesian`
* After taking a look at rotating the y-label, it seems there isn't an easy way to do this without the label taking up the same amount of space as if it were horizontal

**Comment by Ro4052** [comment]
I've managed to get a decorate function that can rotate the y-label in the `chartCartesian` case. I was working the `chart` example. The decorate unfortunately involves wrapping the label in a new div.

This first snippet has the same problem as the `chartSvgCartesian` and `chartCanvasCartesian` in that the label breaks and is then clipped:

```
.decorate(container => {
  container
    .append('div')
    .attr('class', 'y-label-container')
    .style('grid-column', 5)
    .style('grid-row', 3)
    .style('width', '1em')
    .style('display', 'flex')
    .style('align-items', 'center')
    .style('justify-content', 'center')
    .append(() => container.select('.y-label').node())
    .style('transform', 'rotate(-90deg)');
});
```

![image](https://user-images.githubusercontent.com/29425751/57770067-5ec5ab80-7707-11e9-8157-69da2f6b7e0b.png)

This second snippet deals with this issue, using more of the available vertical space:

```
.decorate(container => {
  container
    .append('div')
    .attr('class', 'y-label-container')
    .style('grid-column', 5)
    .style('grid-row', 3)
    .style('width', '1em')
    .style('display', 'grid')
    .style('align-items', 'center')
    .style('justify-content', 'center')
    .append(() => container.select('.y-label').node())
    .style('writing-mode', 'vertical-rl')
    .style('transform', 'rotate(180deg)');
});
```

![image](https://user-images.githubusercontent.com/29425751/57770174-9d5b6600-7707-11e9-90d7-cf9f82e64e93.png)

Both of these snippets are based on code from `cartesianBase` with some minor changes.

**Comment by Ro4052** [comment]
One suggestion would be to follow the implementation of `cartesianBase` and wrap the label in a `.y-label-container` div, allowing the user more control over styling. Even if by default, `chartCartesian` provides no more styling than it currently does.

**Comment by Ro4052** [comment]
I've found another difference between `chartCartesian` and the legacy components that I believe relates to the chart title. If I set `xOrient` to top for `chartCartesian` both the axis and label are on the top of the chart. If I do the same for the legacy component, the axis moves but the label stays at the bottom which I assume is so it doesn't clash with the chart title.

`chartCartesian`:
![image](https://user-images.githubusercontent.com/29425751/57868328-aed16a80-77fa-11e9-98c7-ff408335fee6.png)

Legacy:
![image](https://user-images.githubusercontent.com/29425751/57868376-c872b200-77fa-11e9-9c7c-b2f260716acb.png)

**Comment by ColinEberhardt** [comment]
> If I do the same for the legacy component, the axis moves but the label stays at the bottom which I assume is so it doesn't clash with the chart title.

I'd consider that to be a bug in the legacy components - not worth fixing IMHO

**Comment by Ro4052** [comment]
Looks like there're two points left:

- Migrate the various D3 blocks examples to `chartCartesian` (I can't do this)
- Enhance the cartesian chart docs, we really need to illustrate some more of the common use cases (what did you have in mind?)
