### ISSUE TITLE
Enhancement request: Use transferControlToOffscreen() to render on canvas

### ISSUE THREAD

**Issue by davepuchyr** [d3fc/d3fc#1283]
Rendering large data sets on the main thread causes the browser to seem to "lock-up".  When the rendering target is a canvas then transferControlToOffscreen() would eliminate the lock-up.  See https://developers.google.com/web/updates/2018/08/offscreen-canvas.

PS Thanks for a creating d3fc!

**Comment by chrisprice** [comment]
Nice suggestion, thanks! I hadn't seen this before. My only concern would
be browser compatibility, Edge and Safari appear to be hold outs at the
moment.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/transferControlToOffscreen

**Comment by ColinEberhardt** [comment]
Thanks, definitely worth considering. You might be interested in this too:

https://github.com/d3fc/d3fc/pull/1282

WebGL is on its way :-)

**Comment by davepuchyr** [comment]
WebGL?!?  Sweet!!!

**Comment by chrisprice** [comment]
Reopening this issue as I think it's likely to gain better adoption soon and it's a nice alternative to web gl if the workload can't be GPU offloaded.

**Comment by chrisprice** [comment]
Here's a [blog post](https://blog.scottlogic.com/2020/03/19/offscreen-canvas.html) detailing how to do it.
