### ISSUE TITLE
Broken link to v14.0.0 in readme.md Migration to D3 version 5 section

### ISSUE THREAD

**Issue by RandomFractals** [d3fc/d3fc#1289]
https://github.com/d3fc/d3fc/blob/master/README.md
...
https://github.com/d3fc/d3fc/releases/tag/v14.0.0

**Comment by ColinEberhardt** [comment]
Thanks for the heads-up. We actually seem to have lost the release notes that are typically published as part of the semver process @chrisprice

**Comment by chrisprice** [comment]
There isn't a semver process anymore 😄 It was removed when we went to monorepo (#1100). I think we decided we weren't getting much value from them at the time.

**Comment by tommclaughlan** [comment]
Looks like this has come out of the change from using 'semantic-version' to having lerna handle publication stuff, with 'conventional-commits'.
Change logs are now found at e.g https://github.com/d3fc/d3fc/blob/master/packages/d3fc-data-join/CHANGELOG.md
and releases look like this: https://github.com/d3fc/d3fc/releases/tag/d3fc%4014.0.44 without release notes.

I suppose an immediate fix would be to drop the link to the release notes from the README.md ?

**Comment by RandomFractals** [comment]
hah! ok! do it then. lol! besides, we all know nobody does d3 v4 and prior anymore. I think there is no point in keeping that note, although I don't know how long your lib has been around for.

I do have a few other q's for you guys I'll log separate tickets for later. mainly, can we export charts svg/png? :)
