### ISSUE TITLE
Move to jest

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#1296]
#1295 has reminded me how old some of our tooling is. It would be nice to get the test runner upgraded as well.

**Comment by ColinEberhardt** [comment]
done

**Comment by chrisprice** [comment]
Not done, that's just the examples currently 🙂

**Comment by jleft** [comment]
I'd be happy to take a look at this, if a contribubtion would be welcome? 😃

**Comment by chrisprice** [comment]
Yes please!

**Comment by chrisprice** [comment]
Ideally -
* We'd just have the one top-level (pre-existing) jest dependency
* Remove the `test` script per package
* One top level `test` script that runs all of the tests across all packages within one instance of jest. It should exclude the examples by default.
