### ISSUE TITLE
Footprint charts

### ISSUE THREAD

**Issue by barthr** [d3fc/d3fc#1318]
Dear d3fc maintainers,

I'm evaluating different visualisation libraries/options for visualising a certain type of analysis on my tool.

The chart type I'm looking at is the "footprint chart". A small example of this is:

![image](https://user-images.githubusercontent.com/9822478/64729330-7ef65300-d4cc-11e9-9602-c3505090ca2a.png)

This chart is basically a detailed version of a candlestick chart. First I decided to do it directly with d3.js but then I found this library which provides a lot of the functionality I would need. 

I was wondering if it's possible to build these kinds of visualisations using d3fc and if so do you guys have any tips for me in approaching this problem.

Thanks in Advance !

Bart

**Comment by chrisprice** [comment]
From what I can gather from the screenshot, there's definitely scope for
reusing done of the d3fc components. I've not come across a chart like that
before though, have you got a link to a more detailed description of it?

I think a reasonable starting point would be to take the ohlc series and
set it's width to 0. That should get you the coloured vertical line. Laying
out the text would be trickier but using decorate on the series to add in a
text element and then using data join on that to add in tspans per row of
text (are those order fills?) might be one way of getting close.

**Comment by barthr** [comment]
Hi @chrisprice, you can find more on footprint charts and their usage here: https://www.purefinancialacademy.com/blog/footprint-charts-and-how-they-are-commonly-used

What I'm visualising are actually trades being made against a certain price. I will try your suggestion and see if it works! Thanks for the quick suggestion

**Comment by JaaduGit** [comment]
hey have you made your footprint chart ?

**Comment by ColinEberhardt** [comment]
Hi @JaaduGit it's not quite the same thing, but a demonstration of the versatility of D3 / D3FC, here's a market profile chart example:

https://blog.scottlogic.com/2017/08/23/market-profile.html
