### ISSUE TITLE
Load older data scrolling horizontally

### ISSUE THREAD

**Issue by KabDeveloper** [d3fc/d3fc#1332]
I want to load old (previous) datas basing on the user need.

The concept is like this:

When user first load the chart, he will see a recent datas

And then, he can drag the chart from left to right to check for previous datas

When he arrive to the last one, detect that and then load older datas, redraw them into the chart, refresh the zooming etc ...

My goal is to detect the event when the user arrive to the last data and drag so he show the previous one ... I need only to detect that event.

Can you help please? I need to show 600 rows only, and then depend on user scrolling horizontally , other datas will be loaded remotly using the last time point.

**Comment by chrisprice** [comment]
Sorry I replied to this by email the other day but it hasn't shown up for some reason...

> You'll need to use a zoom behaviour and observe the events that it raises. This example from the old website might give you a starting point -
>
> https://beta.d3fc.io/examples/zoom/index.html

**Comment by KabDeveloper** [comment]
@chrisprice I appreciate your reply, thank you.

I will make tests in this side.
