### ISSUE TITLE
scale/scale.coordinate/scale.component naming is confusing

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#1362]
Calling `scale(program)` applies the scale to the `scale.coordinate`th value of `vec4 gl_Position`. Calling `scale.component(program, component)` applies the scale to the `scale.coordinate`th value of `vecN component` (making the implicit assumption that `N` > `scale.coordinate`).

The scales generate scaling uniforms based upon the `scale.coordinate`, with no-op values filling in the other values. Internally the `scale.coordinate` value is also used to generate the uniform identifiers. A templated shader is then appended to the program containing the generated identifiers.

I find the naming and the scope of `scale.coordinate` to be confusing. I also think that special-casing `scale(program)` to implicitly apply to `gl_Position` feels like magic (in a bad way). 

I propose the following changes -

* The signature of `scale(...)` is changed to always accept an `identifier`.
* The `scale.coordinate` property is removed and `scale(...)` is additionally changed to accept an `index`.

**Comment by chrisprice** [comment]
I'm happy to be challenged on the naming, this might be useful - https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)

**Comment by jamesmporter** [comment]
Earmarked for Adil.

**Comment by josted** [comment]
Just to clear up some confusion:

> Calling **scale.component(program, component)** applies the scale to the scale.coordinateth value of vecN component

 This should be **scaleComponent(program, component)**
