### ISSUE TITLE
Performance tips for WebGL API

### ISSUE THREAD

**Issue by OliverForeman** [d3fc/d3fc#1364]
When the d3fc-webgl API is stabilised it could be useful to inform users of ways to improve performance

e.g. Setting `defined(() => true)` when you know the data doesn't have any null values

**Comment by chrisprice** [comment]
Add to the `packages/d3fc-webgl/README.md`

**Comment by chrisprice** [comment]
Covered here https://github.com/d3fc/d3fc/tree/master/packages/d3fc-series#webgl-rendering
