### ISSUE TITLE
Optimisation of seriesWebglX implementations

### ISSUE THREAD

**Issue by OliverForeman** [d3fc/d3fc#1366]
Currently the `seriesWebglX` implementations do not employ any diffing to check if data has changed. This means that we perform a lot of data processing tasks on every render eg. running `defined` and creating data arrays. The performance of the series can suffer because of this. At the moment we can only avoid this by directly using the underlying API, `glX`.

Therefore to improve performance we should implement a way to compare data between renders.

1. Store data between renders (eg. using `__data`) allowing us to diff the new data and the old data for changes
    - This will not provide the best optimisation
    - Still potentially have to iterate over the whole data set
2. Use a symbol to identify the data (eg. hash)
    - User can provide a method for generating a symbol
    - Only have to compare symbols to check if data has changed
    - Avoids having to iterate the data set if data hasn't changed

**Comment by chrisprice** [comment]
Sorry for the confusion when I said symbol I was referring to
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol
