### ISSUE TITLE
Comparisons on scaled values

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#1373]
The following series perform comparisons on scaled rather than raw values -

* `glCandlestick` - in the computation of `aColorIndicator` & `aYDirection`
* `glOhlc` - in the computation of `aColorIndicator`

**Comment by chrisprice** [comment]
`glCandlestick`-`aYDirection` should be fixed by #1371.

I can't think of an example where you would ever want the colour not to match the relative on-screen magnitudes of the values.

**Comment by OliverForeman** [comment]
This is no longer an issue, both `candlestick` and `ohlc` now use the values passed directly to the shaders for their comparisons.

```
vColorIndicator = sign(aCloseValue - aOpenValue);
```
