### ISSUE TITLE
baseAttributeBuilder.type is not respected

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#1375]
`projectedAttributeBuilder` does not consider `baseAttribute.type()` when constructing the `projectedData`.

**Comment by OliverForeman** [comment]
Attribute types are restricted to `float`, `vectors`, and `matrices`, do we have any use cases for the types other than `float`

**Comment by chrisprice** [comment]
This ticket should also cover optimising our usage of array types (to reduce their transfer time to the GPU). Anything that is expressed in screen pixels (e.g. line widths, point sizes, etc.) or is a flag (e.g. defined) should be changed to a smaller type (e.g. uint8/16).

**Comment by jamesmporter** [comment]
After experimenting with this, it seems that a `Float32Array` is necessary for `ARRAY_BUFFER` and `Uint16Array` for the `ELEMENT_ARRAY_BUFFER`. However, further investigation may reveal a way to solve this problem.
