### ISSUE TITLE
Optimise two-stage generation of attributes

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#1377]
Currently attributes values are transformed by `d3fc-series` and then subsequently transformed by `d3fc-webgl`. This has a computation and memory cost.

**Comment by chrisprice** [comment]
This work should be held until `ANGLE_*` is investigated (see #1369)

**Comment by OliverForeman** [comment]
`elementConstantAttributeBuilder` should not project the data if the value function is the default identity function and `components = 1`, `verticesPerElement = 1`, and `offset = 0`.

**Comment by chrisprice** [comment]
* Accept a second argument when passing in `data` to `elementConstantAttributeBuilder` which is the projection function.
* Remove `value` (using the above in its place).
