### ISSUE TITLE
Crosshair with snapping in latest version

### ISSUE THREAD

**Issue by parliament718** [d3fc/d3fc#1388]
In previous version of d3fc my code was using fc.util.seriesPointSnapXOnly for snapping the crosshair.

This appears to be gone in the latest version of d3fc (or maybe I'm missing it in one of the standalone pckages).

I'm using the canvas implementation (annotationCanvasCrosshair) and it seems to also be missing the "snap" function where it was previously used like so:

```  
  fc.tool.crosshair()
     .snap(fc.util.seriesPointSnapXOnly(line, series);)

```

Additionally, "on" is also not available, so I can't attach events like trackingstart, trackingend, etc.

How can I implement a snapping crosshair now? The canvas version of the components are badly lacking examples. Does anyone have an example showing a snapping crosshair via Canvas rendering? 

Thank you.

**Comment by chrisprice** [comment]
You're correct that the functionality was removed. The former crosshair component was split into its constituent parts to better align with a uni-directional data flow<sup>1</sup>. 

If you want to restrict snapping to specific values, you can use [d3-array's search methods](https://github.com/d3/d3-array#search) to find the closest data point.

<sup>1</sup> Component events (e.g. the cursor moving over the chart) update a top-level data structure (e.g. `data.crosshair = { x: d3.event.clientX, y: d3.event.clientY }` and trigger a top level redraw of the updated data structure (e.g. `selection.data(data).call(chart)`).

**Comment by parliament718** [comment]
@chrisprice 

This question was anwered on [stackoverflow](https://stackoverflow.com/a/60166125/1267778) with an [example](https://codepen.io/timur_kh/pen/YzXXOOG). 

Only thing left to do with this crosshair is set the color of the labels. Is this possible?
There are exposed decorate functions for the point and each individual crosshair line, however there is no ```labelDecorate``` to set the color of the label text (from xLabel/yLabel). 

Is there any way to work around this, and if not, any chance you could expose ```labelDecorate```?

**Comment by chrisprice** [comment]
> @chrisprice
> 
> This question was anwered on [stackoverflow](https://stackoverflow.com/a/60166125/1267778) with an [example](https://codepen.io/timur_kh/pen/YzXXOOG).
> 
> Only thing left to do with this crosshair is set the color of the labels. Is this possible?
> There are exposed decorate functions for the point and each individual crosshair line, however there is no `labelDecorate` to set the color of the label text (from xLabel/yLabel).
> 
> Is there any way to work around this, and if not, any chance you could expose `labelDecorate`?

Any chance you could raise another issue for that please?
