### ISSUE TITLE
Handling of defined is inconsistent in d3fc-series WebGL implementations

### ISSUE THREAD

**Issue by OliverForeman** [d3fc/d3fc#1412]
For `area` and `line`, `defined` is handled as a property of `glArea` and `glLine` respectively. For the other implementations it is handled via the `base`.

This also affects the data passed to the decorate function as `area` and `line` are passed the full data, whereas the other implementations are passed `filteredData`

**Comment by chrisprice** [comment]
For consistency, always add a `defined` buffer and discard at the shader level. This means that `decorate` will always see the unfiltered `data`.
