### ISSUE TITLE
@d3fc/d3fc-series has bug that d3fc package does not

### ISSUE THREAD

**Issue by parliament718** [d3fc/d3fc#1437]
I'm seeing a bug with webgl rendering using the standalone package that is not there in the main package. If I use 

`import { seriesWebglCandlestick } from '@d3fc/d3fc-series';` //version 4.4.14

I get the error:

[.WebGL-0x7fe71674f600]GL ERROR :GL_INVALID_OPERATION : glDrawElementsInstancedANGLE: attempt to access out of range vertices in attribute 7

However, if I use the same function from the main d3fc package:

```
import * as fc from 'd3fc'; //version 14.1.25
const generator = fc.seriesWebglCandlestick()
...
```

The error disappears

**Comment by chrisprice** [comment]
Sorry I'm unable to reproduce this. All of the gl code is in the d3fc-webgl package so my guess would be you've got a mismatched or older version of d3fc-webgl. I can dig a bit further if you're able to reproduce it in a codepen or equivalent?

**Comment by parliament718** [comment]
[d3fc-issue-1437.zip](https://github.com/d3fc/d3fc/files/4183547/d3fc-issue-1437.zip)

Sure, I uploaded a project. Unfortunately I can't reproduce the exact error I was having in my other project, however, I am getting a different error when I do the exact same thing (use ```seriesWebglCandlestick``` instead of ```fc.seriesWebglCandlestick```)

Perhaps they're related.


To run: 

```
npm install
npx webpack
open -a "Google Chrome" index.html
```

**Comment by OliverForeman** [comment]
I believe the error seen in the example is caused by the way some imports are being handled within the WebGL functionality. PR #1474 should resolve this issue.
