### ISSUE TITLE
Webgl based gridlines

### ISSUE THREAD

**Issue by parliament718** [d3fc/d3fc#1438]
Is there a built-in way to render grid lines using webgl? I'm trying to move over from canvas and noticed there is no annotationWebglGridline.

I'm aware of the lack of feature parity with the webgl components, but is there any progress or beta code I could use for this one? Generally, what are some of the next things being worked on for d3fc-webgl? 

Alternatively, is there any way to combine them? Like:

`seriesMulti().series([ canvasGridlineSeries, webglCandlesSeries ])`

This doesn't work because ultimately I need to call .webglPlotArea() on the cartesian

**Comment by OliverForeman** [comment]
It is possible to combine the use of a Canvas series with a WebGL series, you can do this by making use of both `webglPlotArea()` and `canvasPlotArea()`. For example if using a cartesian chart:
```javascript
chartCartesian(xScale, yScale)
  .webglPlotArea(webglSeries)
  .canvasPlotArea(canvasSeries);
```

You can see a full example of this that will be added in PR #1441

**Comment by parliament718** [comment]
Works like a charm, thank you.

**Comment by parliament718** [comment]
@OliverForeman  I did just notice however that the canvas series is drawn on top of the webgl series even if I call canvasPlotArea() before webglPlotArea(). The canvas series always renders on top. It's a minor issue but is that a bug or is there something to do on my side? 
![Screen Shot 2020-02-07 at 4 22 25 PM](https://user-images.githubusercontent.com/3580270/74066921-130a0f00-49c6-11ea-9e88-32cf17914c17.png)

**Comment by chrisprice** [comment]
@parliament718 see #1453 for the fix/documentation
