### ISSUE TITLE
Discontinous time scale not working with WebGL series

### ISSUE THREAD

**Issue by parliament718** [d3fc/d3fc#1442]
I'm converting a canvas candle chart to webgl. Hitting an issue using discontinous time scale

Here's a working pen with WebGL rendered candles using a regular d3.scaleTime().

https://codepen.io/parliament718/pen/RwPwdvR

Problem is if you uncomment the lines to use a discontinous scale instead, errors appear

```
var x = d3.scaleTime(); //works with webgl

var x = fc.scaleDiscontinuous(d3.scaleTime())
       .discontinuityProvider(fc.discontinuitySkipWeekends());  //doesnt work with webgl (but does work with canvas)
```

**Comment by chrisprice** [comment]
Good spot. There's a bug in the webgl series, looks like the boolean logic was confused in a refactor. Instead of -

```
if (isIdentityScale(xScale.scale) && isIdentityScale(yScale.scale) && !equals(previousData, data)) {
```

I think it should be -

```
if (!isIdentityScale(xScale.scale) || !isIdentityScale(yScale.scale) || !equals(previousData, data)) {
```

**Comment by chrisprice** [comment]
Until this bug is fixed that means only scales that can be mapped completely to their gl equivalents will work. See `packages/d3fc-webgl/src/scale/scaleMapper.js` for what's supported (i.e. linear, log, power, time).
