### ISSUE TITLE
Custom axis not working with cartesian

### ISSUE THREAD

**Issue by parliament718** [d3fc/d3fc#1444]
I'm trying to provide a cartesian chart with a custom axis however it doesnt seem to be working like shown in the documentation here: https://d3fc.io/api/axis-api.html#axis

Here's a pen: https://codepen.io/parliament718/pen/NWqPVQq

It works when providing ```fc.axisRight``` directly but it does not work on the return value of said function.

In the pen, if you use variables ```customXAxis``` or ```customYAxis```, errors appear in the console.

**Comment by chrisprice** [comment]
It is working as expected but I agree it's not too clear. From the [documentation](https://d3fc.io/api/chart-api.html#chartCartesianSettings) -

> Constructs a new Cartesian chart with the given scales and axis components.
> 
> If xAxis is specified, it must be an object with the required **x-axis factory function** (left if yOrient="left" or right if yOrient="right").
> 
> If yAxis is specified, it must be an object with the required **y-axis factory function** (top if xOrient="top" or bottom if xOrient="bottom").

**Comment by parliament718** [comment]
Sorry, I don't understand. I updated the pen to use the customYAxis with a custom decorate function and it is now broken. Doesn't seem to be working as expected.

**Comment by parliament718** [comment]
@chrisprice 

Sorry, I don't understand. I updated the pen to use the customYAxis with a simple decorate function and it is now broken. Doesn't seem to be working as expected.

I can't make any sense of the doc at all. If I want to specify a yAxis on the right, what does top and bottom have to do with it? To me those points seem to be mixed up, but the code doesn't work either.

**Comment by chrisprice** [comment]
The reason the API is a little odd is that you need to pass the scale into the factory function for the component. So we can't just accept an instance of the axis (or at least that was our rationale at the time... #1461).

Here's how it would need to be specified currently -

```
const customYAxis = scale => fc.axisRight(scale).decorate(() => {
  console.log('do something');
});

const config = {
  xScale: x, 
  yScale: y,
  yAxis: { right: customYAxis },
  xAxis: { bottom: fc.axisBottom }
};
```

**Comment by parliament718** [comment]
@chrisprice Here's a pen with your suggestion: https://codepen.io/parliament718/pen/vYOLwdx

It still doesn't work. The axis does appear now, but ```decorate``` is never called. Instead, the ```customYAxis``` function is called every render.

**Comment by parliament718** [comment]
@chrisprice  Is this a bug or am I missing something?

**Comment by chrisprice** [comment]
> Instead, the customYAxis function is called every render.

I would expect this behaviour, the chart is [asking for an axis from the factory function every render in case you've changed the axis position](https://github.com/d3fc/d3fc/blob/master/packages/d3fc-chart/src/cartesian.js#L120).

> The axis does appear now, but decorate is never called. 

Sorry I misread your code and misunderstood its intention. The decorate function you are specifying is being [overwritten](https://github.com/d3fc/d3fc/blob/master/packages/d3fc-chart/src/cartesian.js#L121) by an [empty function](https://github.com/d3fc/d3fc/blob/master/packages/d3fc-chart/src/cartesian.js#L26). 

If you are just looking to decorate the default axis then you can use the `x/yDecorate` properties on the chart -

```
  .yDecorate(selection => {
      alert('custom yAxis decorate');
    })
```

N.B. I spotted you've defined 2 decorate functions on the chart (i.e. called `decorate` twice with two different values), note the first decorate function will be ignored.
