### ISSUE TITLE
Add labelDecorate for styling the labels in annotationCanvasCrosshair 

### ISSUE THREAD

**Issue by parliament718** [d3fc/d3fc#1463]
The canvas crosshair has 3 decorate methods, one for the point and 2 for the lines. 
I think there needs to be another one added called labelDecorate to allow setting styles for the labels rendered via xLabel/yLabel

**Comment by chrisprice** [comment]
I believe the text is filled but the line is stroked so you should be able to use `fillStyle`/`strokeStyle` to target them separately.

**Comment by parliament718** [comment]
This turns out to be the case. I thought I tried this but must have overlooked something. Thanks
