### ISSUE TITLE
Handling of errors for shader compiling and attribute/uniform binding

### ISSUE THREAD

**Issue by OliverForeman** [d3fc/d3fc#1470]
Currently there is no handling for any errors/warnings that occur during shader compilation or when binding attributes/uniforms. This results in the program potentially exiting without rendering and outputting a WebGL generated message.

Ideally we want to be able to automatically recover from these potential error states but not if it comes with a significant performance hit.

**Comment by OliverForeman** [comment]
If we ever encounter an error that results in a blank screen/no draw we should evaluate how to handle this. If the default error given by the browser/WebGL is appropriate then this can be left, otherwise we should throw an error ourselves to indicate what caused the error.

**Comment by chrisprice** [comment]
> Currently there is no handling for any errors/warnings that occur during shader compilation or when binding attributes/uniforms. This results in the program potentially exiting without rendering and outputting a WebGL generated message.
> 
> Ideally we want to be able to automatically recover from these potential error states but not if it comes with a significant performance hit.

Compilation/linking errors triggers warnings from the browser in the console. For further detail, set the [`program.debug(true)` flag](https://github.com/d3fc/d3fc/tree/master/packages/d3fc-webgl#webglProgramBuilder_debug).

**Comment by chrisprice** [comment]
> If we ever encounter an error that results in a blank screen/no draw we should evaluate how to handle this. If the default error given by the browser/WebGL is appropriate then this can be left, otherwise we should throw an error ourselves to indicate what caused the error.

We should raise specific examples of this happening as separate issues
