### ISSUE TITLE
webgl point missing symbols

### ISSUE THREAD

**Issue by adilparvez** [d3fc/d3fc#1476]
Below symbols are missing implementations.

![image](https://user-images.githubusercontent.com/6894766/75995248-0e1c7a80-5ef4-11ea-8bf0-cedac18efaa4.png)
![image](https://user-images.githubusercontent.com/6894766/75995272-1674b580-5ef4-11ea-93fc-124a9ed122cd.png)
![image](https://user-images.githubusercontent.com/6894766/75995281-1aa0d300-5ef4-11ea-8c0a-d78ee2433d4c.png)

**Comment by adilparvez** [comment]
Diamond has been implemented.

**Comment by chrisprice** [comment]
And wye
