### ISSUE TITLE
Boxplot fill/stroke colouring issue

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#1477]
Following the logic within the boxplot shaders, it is not obvious why the perimeter line on the box segment is using the stroke rather than the fill colour. This needs investigating to avoid future maintainability issues.

**Comment by chrisprice** [comment]
The current implementation is broken, see the following screenshot (the triangle consisting of vertex indices 24, 26, 27 have been commented out) -

![image](https://user-images.githubusercontent.com/433457/76337266-02172b00-62ef-11ea-9b64-0ff5f03a9289.png)

Specifically moving the `clamp` operation into the fragment shader was masking rather than fixing the underlying issue. There was a typo in the assignment to `canStroke`, `vCanFill` was being used rather than `canFill` -

```
float canFill = clamp(vCanFill, 0.0, 1.0);
float canStroke = 1.0 - vCanFill;
```

We want to -

* Mitre the corners on each elbow joint, so each side of the box becomes a trapezium sharing vertices with its adjacent trapeziums.
* Specify the fill rectangle as being exclusively the centre of the box.

**Comment by chrisprice** [comment]
Temporary fix would be to remove the fill. Long term fix would be to do the above.

**Comment by adilparvez** [comment]
Reverted, colouring not possible now.
