### ISSUE TITLE
WebGL point rendering slower in 14.2 vs. 14.1.10

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1498]
Here is an example that has 1m points with a simple zoom:

https://codepen.io/colineberhardt-the-bashful/pen/bGdmNgp

This renders at ~60fps on my machine.

Here's the same example with 14.2:

https://codepen.io/colineberhardt-the-bashful/pen/VwLEYpN

Which is pretty sluggish in comparison.

**Comment by ColinEberhardt** [comment]
A very brief performance analysis shows that much of the time is now being spent on the GPU:

![image](https://user-images.githubusercontent.com/1098110/77399575-a1352b80-6da1-11ea-9dff-141a8f4ebb25.png)

Each frame is ~ 5ms JS, and ~ 160ms GPU

**Comment by ColinEberhardt** [comment]
i've done a very crude performance measure using [stats.js](http://mrdoob.github.io/stats.js/) 

```
var stats = new Stats();
stats.showPanel( 0 ); // 0: fps, 1: ms, 2: mb, 3+: custom
document.body.appendChild( stats.dom );

const redraw = () => {
  stats.begin();
  d3
    .select("d3fc-group")
    .node()
    .requestRedraw();
  stats.end();
}
```

Here is the resulting FPS for various versions ...

4.1.10 - 43
4.1.11 - 44
4.1.12 - 45
4.1.13 - 126 (?!)
4.1.14 - 124 
4.1.15 - 125 
4.1.16 - 123 
4.1.17 - 124 
4.1.18 - 122 
4.1.19 - 125 
4.1.20 - 125 
4.1.25 - 125 
4.1.28 - 125 
4.1.29 - 23 
4.1.30 - 18 

It drop significantly from 4.1.28 to 4.1.29

**Comment by chrisprice** [comment]
The big bump from 45 to 126 was probably from moving the defined calculation behind the equality check (bec5360a). 

It's harder to say what triggered the drop from 125 down to 23, digging into it now. It's one of these -
```
ec6447ef docs: update series webgl docs
6410735c docs: clarify some edge cases
a034e1d5 docs: webgl docs (#1458)
4f2f5cd0 fix: always use instanced rendering to fix fill/stroke
ccb08123 refactor: renamed webgl package exports
50690bf9 refactor: rename capWidth to cap
aacaacd6 feat: add fill/strokeColor decorators
890d3a25 feat: support initialValue for constantAttribute
403ac758 refactor: externalise attributes
8c945150 refactor: add aDefinedNext
17a1a3a1 refactor: *Attribute only accepts programBuilder
6bd1c8ed refactor: glScales take identifier and component arguments
e8afc16f fix: throw if invalid orient
972402d0 refactor: rename elementIndicesBuilder to elementIndices
a37dd6c5 refactor: rename uniformBuilder to uniform
9f043f26 feat: add useful error messages to bufferBuilder
9da9243d refactor: add aDefinedNext
c6d377e6 refactor: consolidate vertex/elementAttribute
435ac138 refactor: rename xConstantAttributeBuilder to xAttribute
8a9e3617 refactor: use slidingWindowECAB in glArea/Line
2f158639 feat: add slidingWindowElementConstantAttributeBuilder
e7dfcb33 refactor: reduce AB APIs to supported props only
3900c0c1 refactor: allow arrayViewFactory.type rebinding
```

**Comment by chrisprice** [comment]
#1505 raised to partially revert 4f2f5cd0
