### ISSUE TITLE
Have a single consistent place for generated screenshots

### ISSUE THREAD

**Issue by adilparvez** [d3fc/d3fc#1527]
Should all of the examples generate screenshots next to them? If so update paths in docs accordingly.

Note: Some of the existing screenshots don't correspond directly to an example, may have been manually taken. Would be good if all were generated from an example in the repo.

**Comment by tredondo** [comment]
Is that why the images are broken on npm?

https://www.npmjs.com/package/@d3fc/d3fc-technical-indicator

**Comment by chrisprice** [comment]
> Is that why the images are broken on npm?
> 
> https://www.npmjs.com/package/@d3fc/d3fc-technical-indicator

Thanks for the report but I think that's a different issue, raised as #1534 .
