### ISSUE TITLE
Create simple streaming example

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#1548]
The example chart referenced in #1531 would make an ideal candidate for porting to d3fc as an example.

https://github.com/finallyayo/realtime-d3-graph/blob/master/app.js

**Comment by melroy89** [comment]
Yes plz :+1: ! I subscribe for notifications.. If I could help you, let me know!

Although I have no clue what kind of type the `chart` variable is: https://github.com/d3fc/d3fc/blob/master/packages/d3fc-site/src/examples/streaming/streaming.js#L46

Could I append this directly to some svg container? Well... Maybe I let you do it >< after all.

**Comment by chrisprice** [comment]
Not the example from above but here's a [simple chart](https://d3fc.io/examples/simple-chart/) and here's the [streaming equivalent](https://d3fc.io/examples/streaming-chart/).

N.B. https://github.com/d3fc/d3fc/issues/1549 covers improving the example template to show the code and readme alongside the rendered version.

**Comment by melroy89** [comment]
@chrisprice Doesn't work in Firefox (but only Chrome).

![image](https://user-images.githubusercontent.com/628926/80514279-91040380-8980-11ea-9cf2-5b2edb218331.png)


**Solution:** Remove `display: flex;` from the body! See PRs.

**Comment by melroy89** [comment]
Strange, when introducing `<!DOCTYPE html>` to the top of HTML page, the chart is broken again in FF. But when I do that, also the chart gets broken in Chrome!

Which is a [doctype declaration](https://www.w3schools.com/tags/tag_doctype.asp), and should work in all cases.

@chrisprice Could you please look into this issue?

Chromium (chart is not correctly getting displayed):
![image](https://user-images.githubusercontent.com/628926/80533411-d97dea00-899d-11ea-8cf7-5b8552cbd3e6.png)

Code:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/seedrandom/3.0.5/seedrandom.min.js"></script>
    <script>Math.seedrandom('a22ebc7c488a3a47');</script>
    <script src="https://unpkg.com/d3@5.16.0" type="text/javascript"></script>
    <script src="https://unpkg.com/d3fc@15.0.1" type="text/javascript"></script>
    <style>
        body {
            margin: 0;
            flex: auto;
        }

        body>* {
            flex: auto;
        }
    </style>
</head>
<body>
    <div id="chart"></div>

    <script src="index.js"></script>
</body>
</html>
```

**Comment by melroy89** [comment]
Or is it just me :S? Can you reproduce it as well?

**Comment by chrisprice** [comment]
It's been a busy couple of days. I can see it's broken as well, got a PR
almost ready which should fix them all.

**Comment by danger89** [comment]
I think you did it! Thanks Chris for all your effort! Close issue?

**Comment by melroy89** [comment]
Yep you did it Chris! Thank you so much for your time and effort! I think you can close this issue.

**Comment by melroy89** [comment]
@ColinEberhardt  Ok, maybe one shout out to Colin, to update the blocks streaming example with the newly created chart by Chris: https://bl.ocks.org/ColinEberhardt/ab7805a9a7af9717e86adc1656fa98d9
