### ISSUE TITLE
Make getting started documentation easily accessible on the website.

### ISSUE THREAD

**Issue by j-n-white** [d3fc/d3fc#1551]
With the simplified new website design the getting started documentation previously available [here](https://d3fc.io/introduction/getting-started.html) is no longer available. Without this introductory information explaining the high level concepts you have to dive straight into the API or an example.

The pages' source can still be read [here](https://github.com/d3fc/d3fc/tree/master/packages/d3fc-site/src/introduction) but it is not easy to navigate.

Is it possible to make this information more easily accessible again?

**Comment by chrisprice** [comment]
Duplicate of #1553. 

See https://github.com/d3fc/d3fc/blob/master/README.md#documentation
