### ISSUE TITLE
Make old documentation available?

### ISSUE THREAD

**Issue by wayspurrchen** [d3fc/d3fc#1553]
Hi! Love this module, it's proven invaluable in some of the work am picking up again after a hiatus. I came back and found that none of the old API documentation links work, and the lack of walk-through style guides that were available make it difficult to get to know the pieces of this API.

I was able to get the examples working locally so I could see the source in a reasonable way, but I had to pull down the repo, install everything, and then bundle the entire repository. This seems like a steep barrier to entry for anyone coming across d3fc for the first time who isn't already invested in using it.

Please consider making the old documentation available; I thought it was really user-friendly and showed off the power and flexibility of df3c, and the composability philosophy outlined in its documentation was one of the first things that drew me to it.

**Comment by melroy89** [comment]
Related: https://github.com/d3fc/d3fc/issues/1551

**Comment by chrisprice** [comment]
All of the old documentation should now be linked from the top-level readme -

https://github.com/d3fc/d3fc#documentation
