### ISSUE TITLE
Bandwidth differs between SVG and WebGL series

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1564]
Here's an SVG series with a 15px bandwidth:

![image](https://user-images.githubusercontent.com/1098110/80861348-f8ae9d00-8c65-11ea-86d4-139c6afda64f.png)

And here's a WebGL series with the same:

![image](https://user-images.githubusercontent.com/1098110/80861370-111eb780-8c66-11ea-9b9d-699dea1dcda9.png)

Also, the high / low 'wick' looks like it has a sub-pixel width

**Comment by chrisprice** [comment]
The sub pixel width is probably down to the `use-pixel-ratio` attribute.

**Comment by chrisprice** [comment]
Thinking about it that's probably what's wrong with bandwidth as well

**Comment by ColinEberhardt** [comment]
fixed via #1576
