### ISSUE TITLE
Could SVG gridline annotation stroke be set on enter not update?

### ISSUE THREAD

**Issue by jleft** [d3fc/d3fc#1577]
The `annotationSvgGridline` component sets the `stroke` attribute of both the x and y lines on update rather than enter:

https://github.com/d3fc/d3fc/blob/f8ddaf6a5f0b58aa0460c5d045364d3f32e17a53/packages/d3fc-annotation/src/svg/gridline.js#L48-L53

https://github.com/d3fc/d3fc/blob/f8ddaf6a5f0b58aa0460c5d045364d3f32e17a53/packages/d3fc-annotation/src/svg/gridline.js#L74-L79

When using the decorate pattern to set the stroke color of the gridlines, the stroke must be set on update rather than enter (I've created [an example on CodeSandbox](https://codesandbox.io/s/pensive-mcclintock-k0g4f?file=/src/index.js) to illustrate this). Given that the stroke set by the component is contant (`#bbb`) it seems unecessary to do this on update; could this be set on enter?

I think this would also be consistent with the line annotation, where the `stroke` attribute is set on enter:

https://github.com/d3fc/d3fc/blob/250e3455624ffbce3ed7e381af6d8946906afafd/packages/d3fc-annotation/src/svg/line.js#L50-L52

**Comment by ColinEberhardt** [comment]
I agree, the stroke should be set on enter - do you want to raise an appropriate PR?

**Comment by chrisprice** [comment]
Looks like we have a similar situation in axis for `domainLine` - 

https://github.com/d3fc/d3fc/blob/4f9117367e25e327fb4fa51d6740a75b1661ab0e/packages/d3fc-axis/src/axisBase.js#L97-L116

**Comment by ColinEberhardt** [comment]
Re-opened as per above comment regarding the axis.

**Comment by jleft** [comment]
I'm happy to look into the axis component.
