### ISSUE TITLE
Annotation value crosshair and last close

### ISSUE THREAD

**Issue by Serg65s** [d3fc/d3fc#1592]
This example doesn't work.( http://bl.ocks.org/ColinEberhardt/875bb098218a94cad7f5) The addXCallout (sel) and addCallout(sel) functions do not put path and text on top of the y-axis and x-axis. How to display the value of the annotation on the axes? Is this possible?

**Comment by chrisprice** [comment]
Does this [example](https://github.com/d3fc/d3fc/pull/1595) demonstrate what you're looking for?

[![Axis annotation example](https://raw.githubusercontent.com/d3fc/d3fc/a875a12659354f42bb44f31e13d912275c959c6e/examples/axis-annotation/screenshot.png)](https://github.com/d3fc/d3fc/pull/1595)

**Comment by Serg65s** [comment]
Yes.
![exmp](https://user-images.githubusercontent.com/68597795/88385084-60343e80-cdb6-11ea-9f5c-fb737226375e.jpg)
 
I would like the values ​​to be displayed on the axes behind the movement of the crosshair

**Comment by chrisprice** [comment]
To track the crosshair you'll just need to feed the crosshair value into the annotation from the example.

**Comment by Serg65s** [comment]
I was unable to use this solution. I did it differently. Pass in the index and invert it

               let lastPoint = scale.invert (dat);
                const calloutDatas = [lastPoint];


                let element = calloutJoin (
                    d3.select (nodes [[selectionIndex]),]
                    calloutDatas
                ) .attr ("transform", d => `translate ($ {scale (d)}, $ {width / 2})`);


It all worked. And you just need to display on the scale. otherwise it works slowly with breaks. In this case, everything is ok

**Comment by Serg65s** [comment]
![chrt](https://user-images.githubusercontent.com/68597795/88692849-373de180-d107-11ea-898d-ea2ba434b529.jpg)

**Comment by Serg65s** [comment]
Thanks for the support. The question is closed. The solution that suits me was found
