### ISSUE TITLE
Uncaught TypeError: fc.pointFill is not a function

### ISSUE THREAD

**Issue by ghost** [d3fc/d3fc#1594]
while trying to re-create an example from [here](https://bl.ocks.org/OliverForeman/f8bc8d69b7df041ada60cc86952c6fee), getting a TypeError: fc.pointFill is not a function

The version of d3fc 14.1.0 from that example works, but not the latest 15.0.10 that https://unpkg.com/d3fc is currently redirecting to. Is this function being deprecated?

**Comment by chrisprice** [comment]
The up to date equivalent can be found in the examples directory -

https://d3fc.io/examples/diamonds/
