### ISSUE TITLE
User svg icons

### ISSUE THREAD

**Issue by Serg65s** [d3fc/d3fc#1597]
Is it possible to add custom svg icons to the series? Not d3 .... namely your own

**Comment by chrisprice** [comment]
We don't currently support the functionality described by [d3-shape](https://github.com/d3/d3-shape#custom-symbol-types) but probably should. PR welcome 😄 

As a workaround you could use a point series and then decorate the path to be whatever shape you wanted. Alternatively if it was a more complex SVG tree, you could just append it and hide the original path.

**Comment by Serg65s** [comment]
Thank you very much for your attention. I tried it for about an hour, but it didn't work out. In particular problems with zoom

**Comment by ColinEberhardt** [comment]
For an example of using decoration to insert SVG shapes, take a look at this chart:

https://colineberhardt.github.io/yahoo-finance-d3fc/

The clock / moon / sun icons SVGs are here:

https://github.com/ColinEberhardt/yahoo-finance-d3fc/blob/master/index.html#L35

The decorate pattern inserts copies of these SVGs using the SVG `use` element:

https://github.com/ColinEberhardt/yahoo-finance-d3fc/blob/897ad0b3bd916edf159bbefc838e763e5030c6b7/chart.js#L71

**Comment by Serg65s** [comment]
Everything worked out. Debugged. Works as expected. The best way is according to your first advice.

**Comment by Serg65s** [comment]
Everything worked out. Debugged. Works as expected. The best way is according to your first advice. Thanks a lot for the tips
