### ISSUE TITLE
Crosshair for multiple charts

### ISSUE THREAD

**Issue by Serg65s** [d3fc/d3fc#1598]
The problem is as follows. There are several graphs on different div, which are located one below the other. The time axis is the same. It is necessary that the vertical crosshair is continuous for all charts, and the horizontal one appears only on those charts on which the focus is currently. Not working yet :( Horizontal crosshair appears on all charts. I saw that the problem was mentioned but did not see a solution  Low Barrel example crosshair issue #645

**Comment by ColinEberhardt** [comment]
Here's a blog post that describes something similar - a collection of small multiples charts that have a trackball that works across all of the charts:

https://blog.scottlogic.com/2017/04/05/interactive-responsive-small-multiples.html

The data 'bound' to each chart has a `trackball` property:

https://gist.github.com/ColinEberhardt/f70c7de43bb91fb7fc7d5bbc3e46a134#file-index-html-L73

A multi-series is used to render the line / area series for each chart, together with the trackball:

https://gist.github.com/ColinEberhardt/f70c7de43bb91fb7fc7d5bbc3e46a134#file-index-html-L119

An `fc.pointer` component handles mouse move interactions, find the closest data-point, and updates the `trackball` property. Finally all the charts are re-rendered:

https://gist.github.com/ColinEberhardt/f70c7de43bb91fb7fc7d5bbc3e46a134#file-index-html-L177

You should be able to use a similar approach. 

i.e. the first step is to create the underlying model that is bound to your charts, including data and crosshair. The next step is to handle UI interactions, update the data and re-render

**Comment by Serg65s** [comment]
Many thanks to Colin. After Your article, a new aspect surfaced that I missed. As soon as I realized that I could not see, everything turned out without much difficulty.

**Comment by ColinEberhardt** [comment]
Great - glad it helped. Closing this issue for now.

**Comment by stereokai** [comment]
@Serg65s any chance you can share how you built that UI with d3fc? It would help me a great deal!
