### ISSUE TITLE
seriesWebglPoint fail to plot with TimeScale at millisecond resolution

### ISSUE THREAD

**Issue by martinschutz78** [d3fc/d3fc#1599]
Hi,

I have an issue with seriesWebglPoint and TimeScale.

This is a fiddle to show my issue : https://jsfiddle.net/z8c57boy/70/

The first chart is printing 10,000 points with random data, 1 point per milli from epoch -> chart is well displayed

The second chart is printing the same 10,000 points, 1 point per milli but from now -> The points are regrouping into a weird "bar"

The third chart is printing the same as the second one, but using canvas instead of webgl -> chart is well displayed

If I put 1 point per minute instead of milli on the second chart : this one is well displayed : https://jsfiddle.net/z8c57boy/69/

Am I doing wrong with dates ?

**Comment by martinschutz78** [comment]
Sorry I fix it with the work around described here : #1491

**Comment by chrisprice** [comment]
FYI - https://github.com/d3fc/d3fc/pull/1600
