### ISSUE TITLE
Discontinuities can result in an axis without any ticks

### ISSUE THREAD

**Issue by Serg65s** [d3fc/d3fc#1601]
xScale = fc.scaleDiscontinuous(d3.scaleTime())
            .discontinuityProvider(fc.discontinuitySkipWeekends());

When I change the scale(zoom), I get a bug. Labels and text on the x-scale disappear. Data is an array with a step of one day. The data is sorted. UTC format.

 How to fix?
![example](https://user-images.githubusercontent.com/68597795/90131187-647bc800-dd74-11ea-9c41-9f78bdadb2ce.jpg)

**Comment by Serg65s** [comment]
No one knows? Or have I missed the information that was already there?

**Comment by ColinEberhardt** [comment]
Hi @Serg65s - I've not seen this problem before, and unfortunately your instructions are a little unclear. In other words, I am not sure what we can do in order to try and reproduce this error.

If you have the time, it would be great if you could try and reproduce this issue in such a way that you could share the code? This would make it much easier to sport the issue and provide a fix or workaround.

**Comment by Serg65s** [comment]
Excuse me. It so happened that only today I saw the answer. Collected the simplest test case.

**main.js**

`const stream = fc.randomFinancial().stream();
var st = stream.take(70);

var data = {
  series: st,
  crosshair: []
};

var x  = fc.scaleDiscontinuous(d3.scaleTime())
            .discontinuityProvider(fc.discontinuitySkipWeekends());
var y = d3.scaleLinear();

// secondary scales for the purposes of computing the zoom
var x2 = d3.scaleTime();
var y2 = d3.scaleLinear();

const xExtent = fc.extentDate()
  .accessors([d => d.date])

const yExtent = fc.extentLinear()
  .accessors([d => d.high, d => d.low])
  .pad([0.2, 0.1])


var zoom = d3.zoom()
  .on('zoom', () => {
    const t = d3.event.transform;
    x.domain(t.rescaleX(x2).domain());

    render();
  });

const line = fc.seriesSvgLine()
    .mainValue(d => d.close)
    .crossValue(d => d.date)

const crosshair = fc.annotationSvgCrosshair()

const gridlines = fc.annotationSvgGridline()
                            .yTicks(0)
                            .xTicks(5);

const mult = [line, crosshair, gridlines]

const multichart = fc.seriesSvgMulti()
			.series(mult)
      .xScale(x)
	    .yScale(y)
    .mapping((data, index, series) => {
      switch(series[index]) {
        case line:
          return data.series;
        case crosshair:
          return data.crosshair;

      } });


const chart = fc.chartCartesian(x, y)
  .svgPlotArea(multichart )
	.decorate((sel) => {
    sel.enter(event)
      .select('#zoom-chart .plot-area')
      .on('measure.range', () => {
        x2.range([0, d3.event.detail.width]);
        y2.range([d3.event.detail.height, 0]);
      })
     .call(zoom)

  });

function render() {
  d3.select('#zoom-chart')
    .datum(data)
    .call(chart)

  var pointer = fc.pointer()
    .on('point', (event) => {
      data.crosshair = event;
      render();
    });

  d3.select('#zoom-chart .plot-area').call(pointer)
}

function updateData() {
  chart
    .xDomain(xExtent(data.series))
    .yDomain(yExtent(data.series));

  x2.domain(chart.xDomain());
  y2.domain(chart.yDomain());

  render();
}
updateData()`


**index.html**

`<!DOCTYPE html>
<meta charset="utf-8">
<style>
  #zoom-chart {
  width: 680px;
  height: 360px;
}

path.line {
  stroke: #f1a500;
}

g.tick path {
  stroke: none;

}

g.tick text{
  fill: #a6a9b1;
}

g.multi line.gridline-y{
  stroke: #e8eaf0;
  stroke-width: 1.5;
}

path.domain {
    stroke: #e8eaf0;
    stroke-width: 1.5;
}


g.annotation-crosshair g.annotation-line>line,
g.annotation-crosshair g.point>path {
    fill: none;
    stroke: gray;
    stroke-width: 1.5;
    stroke-opacity: 1;
    stroke-dasharray: 1, 2;
}
g.annotation-line>g>text {
    font: 10px sans-serif;
    fill:none;
}
  </style>
<body>

<script src="d3.js"></script>
<script src="d3fc.js"></script>

<d3fc-svg id="zoom-chart" class="chart large" ></d3fc-svg>

<script src="main.js"></script>

</body>

`

**Comment by chrisprice** [comment]
Thanks for providing the code. It is often easier to debug the issue if you can present it as a codepen (or equivalent) running example.

As it is, in this case I would assume the axis ticks are not appearing because the tick values that the scale has produced for the domain (which changes as you pan/zoom) are being hidden by the discontinuity. See https://github.com/d3/d3-scale#time_ticks.

**Comment by Serg65s** [comment]
This is a very annoying feature that significantly reduces the value of .discontinuityProvider (fc.discontinuitySkipWeekends ());
for the timeline, reproduces stably on daily data. I assume that the whole problem is hiding the range of no value and d3 not working properly in this case due to the resulting shift. Is it because d3 cannot correctly determine the range to be displayed? Maybe you need to additionally indicate what should be displayed in this case? Perhaps you should override this with something like this?

            var dailyStep = 864e5,
                          dailyTickSteps = [
                              dailyStep, // 1-day
                              6048e5, // 1-week
                              2592e6, // 1-month
                              7776e6, // 3-month
                              31536e6 // 1-year
                          ],
                          intradayTickSteps = [
                              1e3, // 1-second
                              5e3, // 5-second
                              15e3, // 15-second
                              3e4, // 30-second
                              6e4, // 1-minute
                              3e5, // 5-minute
                              9e5, // 15-minute
                              18e5, // 30-minute
                              36e5, // 1-hour
                              108e5, // 3-hour
                              216e5, // 6-hour
                              432e5, // 12-hour
                              864e5 // 1-day
                          ];
I still don't see a solution that would be universal. It is clear only that this is related to the clamp of the array that hides the gaps

**Comment by ColinEberhardt** [comment]
> As it is, in this case I would assume the axis ticks are not appearing because the tick values that the scale has produced for the domain (which changes as you pan/zoom) are being hidden by the discontinuity.

I can confirm that this is the case - if you use a continuous scale, you can see that the ticks are rendered and occur on Sunday's over the weekend:

![image](https://user-images.githubusercontent.com/1098110/93603245-a7f0d400-f9bb-11ea-872c-56916763163e.png)

With a discontinuous axis we use the following logic to filter out ticks that occur within the discontinuity:

https://github.com/d3fc/d3fc/blob/master/packages/d3fc-discontinuous-scale/src/tickFilter.js#L6

Removing the filter results in the ticks being rendered:

![image](https://user-images.githubusercontent.com/1098110/93603526-074ee400-f9bc-11ea-8cf2-522d9aaeb081.png)

This looks like a good solution in this specific case. I'll have a think about whether we should change the behaviour here.

**Comment by chrisprice** [comment]
This has been discussed before I think - https://github.com/d3fc/d3fc/issues/1167. I'm sure there was also an issue that popped up a few weeks back along the same lines but I can't find it from a quick search

**Comment by chrisprice** [comment]
Found it - https://github.com/d3fc/d3fc/issues/1464
