### ISSUE TITLE
Is there an example of pan / drag / zoom on axes independently? 

### ISSUE THREAD

**Issue by artemiusgreat** [d3fc/d3fc#1603]
There is an example of how to do zoom on one axis and pan on another. 
https://stackoverflow.com/a/35445448/437393

Meanwhile, it's for D3 v3 and it uses `behavior` which doesn't seem to be available now, so I was wondering if there is an example of how to do it in the latest version?

**Comment by ColinEberhardt** [comment]
The way that D3 brush (pan) and zoom works makes this a little tricky - they apply a transformation that is 'stashed' on the DOM node itself. As a result, applying multiple interactions causes a conflict.

I created a solution to this in response to a StackOverflow question a little while back, which might be what you need: https://stackoverflow.com/a/61140796/249933

**Comment by artemiusgreat** [comment]
Thank you
