### ISSUE TITLE
Use dates as numbers, but format them as dates in UI

### ISSUE THREAD

**Issue by artemiusgreat** [d3fc/d3fc#1604]
Hi. Let's take this example. 
https://d3fc.io/examples/series-canvas-candlestick/

It defines X scale as a time scale. 
```
const xScale = d3
    .scaleTime()
    .domain(fc.extentDate().accessors([d => d.date])(data));
```
To prevent multiple tick to date conversion in my zoom handler, I'd like to always work with number, but keep UI showing these numbers as dates. So, I change the code above to linear scale. 
```
const xScale = d3
    .scaleLinear()
    .domain(fc.extentLinear().accessors([d => d.date.getTime()])(data));
```
Everything works fine, but now I have an X scale showing numbers instead of dates. **The question is, how to add mapper or formatter that would show these numbers as dates in UI?** I see some examples of `d3.tickFormat`, but not sure how to apply it in `d3fc`.

**Comment by ColinEberhardt** [comment]
Yes you can set the X tick format, I've responded your question on StackOverflow: https://stackoverflow.com/questions/63620443/use-dates-as-numbers-but-format-them-as-dates-in-ui/63621132#63621132
