### ISSUE TITLE
Mockdate latest release has broken website examples

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#1605]
d3fc depends on Mockdate v2.x, and site examples have script tags referencing `src/mockdate.js`. However, as of Mockdate v3 the JS entry point is now; `"main": "lib/mockdate.js"`

The site build process ensures that we always pull in the latest version of MockDate:

https://github.com/d3fc/d3fc/blob/d9d3b56f15bcf81b824e128435f8ca1b10cd6f71/scripts/site.sh#L9

As a result we have a version mismatch and the examples are broken

**Comment by artemiusgreat** [comment]
I'm not using mockdate here, but still have an error... 
https://codepen.io/artemiusgreat/pen/jOqBJaa 
Local bundle taken 1 week ago works fine.

**Comment by chrisprice** [comment]
> I'm not using mockdate here, but still have an error...
> https://codepen.io/artemiusgreat/pen/jOqBJaa
> Local bundle taken 1 week ago works fine.

Pinning d3 to version 5 works i.e. https://unpkg.com/d3@5
