### ISSUE TITLE
Is it possible to override data point renderer?

### ISSUE THREAD

**Issue by artemiusgreat** [d3fc/d3fc#1608]
Does D3FC expose drawing context that would allow to specify how particular data point, e.g. OHLCV item, will be rendered? 

This is an example of what I mean. 
http://dygraphs.com/tests/plotters.html

**Comment by ColinEberhardt** [comment]
Yes, D3FC does allow you to customise how series are rendered, via a technique we call the 'decorate pattern':

https://github.com/d3fc/d3fc/blob/master/docs/decorate-pattern.md

You can see it in action via this tutorial:

https://github.com/d3fc/d3fc/blob/master/docs/building-a-chart.md

If you have something specific in mind, let me know.

**Comment by artemiusgreat** [comment]
I'm thinking about placing some marks, e.g. up and down arrows, over a candle chart to show where a position in stock was open and where it was closed. 

Example of how Meta Trader shows deals on the chart. 
https://c.mql5.com/3/262/image__8.png 

Perhaps, using a time series displaying data points of custom shapes, e.g. arrows, and switch between up and arrow button depending on open and close price of the candle. 
https://d3fc.io/examples/series-canvas-point-size-type/

Could you give some a tip regarding how to rotate the triangle here upside down when the candle is red? 
https://codepen.io/artemiusgreat/pen/rNeyPrz 

I see that, e.g. here, decorate allows to select `path` object, but it's not available on canvas. Is it possible to get a selection on a canvas, compare `open` and `close` values, and transform triangle? 
https://d3fc.io/examples/building-a-chart/

**Comment by artemiusgreat** [comment]
I found an example of decoration and tried to do something simple, but looks like it rotates the entire canvas, not just one symbol. 
https://codepen.io/artemiusgreat/pen/BaKwzKb

**Comment by artemiusgreat** [comment]
Ok. Found. 
https://codepen.io/artemiusgreat/pen/BaKwzKb
