### ISSUE TITLE
How to change annotation labels position

### ISSUE THREAD

**Issue by mortezae** [d3fc/d3fc#1610]
Hello
The default position of annotationLine and annotationCrosshair is top axis. How can I move it to bottom axis?

**Comment by ColinEberhardt** [comment]
If you look at the SVG constructed by a line annotation you can see that it creates 'handle' containers at either end of the line, one of which contains the text label by default:

~~~
<g class="annotation-line vertical" style="stroke: rgb(187, 187, 187);">
   <line y2="-186"></line>
   <g class="bottom-handle" style="stroke: none;"></g>
   <g class="top-handle" transform="translate(0, -186)" style="stroke: none;">
      <text text-anchor="middle" x="0" y="9" dy="0.71em">label text</text>
   </g>
</g>
~~~

You can use the decorate pattern to select the container that doesn't contain a label by default and add one. Here's a worked example:

https://github.com/d3fc/d3fc/blob/master/docs/building-a-chart.md#decorate-pattern

I'm considering whether we should add a text label to each handle by default to make this easier to do.

**Comment by mortezae** [comment]
Thank a lot for your great work, and nice guidance.
