### ISSUE TITLE
Sync multiple charts

### ISSUE THREAD

**Issue by artemiusgreat** [d3fc/d3fc#1613]
**What is the recommended way to sync multiple charts by X axis?** 

Here is an example of a real-time chart that has 3 viewports. Can be zoomed using axes and panned using the mouse. 
https://codepen.io/artemiusgreat/pen/jOqBJaa 

After producing ~70 bars it stops and I try to scale one of the viewports, e.g. window with candles. At this moment, the main viewport should send a notification to the other two viewports to scale the same way and it does this, I can see it in the browser's console. Unfortunately, for some reason, dependent viewports don't scale...

**Comment by Serg65s** [comment]
On child charts, call zoom in the decorate section for mayChart = fc.chartCartesian ()
.decorate (sel => {
                sel.enter ()

                    .select ('. plot-area') ..call (this.zoom)
Where

    this.zoom = mainChart.zoom;

And changing the scale for the child

rescale (t) {
        this.xMayScale.domain (t.rescaleX (this.x2) .domain ());
        this.render ()
    };

Where
this.render = function () {

            d3.select (this.sel)
                .datum (this.dataset)
                .call (this.mayChart);

 this.pointerMay = fc.pointer ()
                .on ('point', (event) => {
                    this.dataset.crosshair = event;

          this.render ();
                    mainChart.render ()
});
}

this.x2 = mainchart.x2
t= mainChart.t

In the base Chart  zoom call zoom children

For example:
main.zoom = d3.zoom()
                .on('zoom', () => {
                    const t = d3.event.transform;
                    xScale.domain(t.rescaleX(main.x2).domain());
                

                    main.allObject.forEach(el => {
                        if (el.typeid == 4) {el.obj.rescale(t)}
                    })
...................................
It works for me like this

**Comment by artemiusgreat** [comment]
Thanks. The only thing is, what if there is no "main" chart? 
In other words, the scaling of **any** chart should scale related charts. 
Is it possible?

**Comment by Serg65s** [comment]
Yes, of course, zoom is a universal method if the scales are compared at least through coefficients. Just don't forget about redrawing. Which method you use to do this depends on the architecture. I have objects so I just run through them and redraw them. which main schedule is not important. What is the first one to take for example.

**Comment by artemiusgreat** [comment]
@Serg65s Finally realized what was wrong. I forgot to call my `Render` method after rescaling :) 
Now it works.
Thanks.

https://codepen.io/artemiusgreat/pen/jOqBJaa
