### ISSUE TITLE
API available in Canvas but not in Web GL

### ISSUE THREAD

**Issue by artemiusgreat** [d3fc/d3fc#1614]
Not sure if it's a bug or feature. Using canvas, I can define multiple series and send them to the plotter. Meanwhile, Web GL works fine only with a single series. If I try to pass **multi-series** to the cartesian chart, it **gives the following error**. 

```
TypeError: webglPlotArea.context(...).pixelRatio is not a function
```

https://codepen.io/artemiusgreat/pen/JjXOxOP

To be more precise. This code works 

```
const multiWebgl = fc
  .seriesWebglMulti()
  .series([candlestick, bars]);

const multiCanvas = fc
  .seriesCanvasMulti()
  .series([canvasBars, gridline]);

const chart = fc
    .chartCartesian(xScale, yScale)
    //.webglPlotArea(multiWebgl)     // multi-series doesn't work in Web GL
    .webglPlotArea(bars)             // single series works fine
    .canvasPlotArea(multiCanvas)     // canvas multi-series works fine
    .svgPlotArea(lowLine);
```

If I try to pass multi-series to `webglPlotArea`, it breaks, even though you can see that the next line doing the same with canvas works fine.

**Comment by artemiusgreat** [comment]
Here is an example of multi-series for Web GL 
https://d3fc.io/examples/series-webgl-multi/ 

Unfortunately, it doesn't have axes... 
In other words, it's not clear how to create a streaming multi-series Web GL chart with X and Y scales, set X to be linear but in UI format it as a date, because... 

* Web GL doesn't provide an interface to create multi-series with `chartCartesian` 
* Without the cartesian chart, there are no axes and they can't be formatted

**Comment by artemiusgreat** [comment]
Example of multi-series for Web GL. 
https://d3fc.io/examples/series-webgl-multi/
Unfortunately, it doesn't have X and Y axes. 

**The issue**

* cartesian chart can't display multi-series for Web GL 
* without the cartesian chart, there is no way to create or decorate the linear X axis to look like a date in UI

Looks like one of the options is to create X and Y axes separately and sync them with Web GL chart, but I'm wondering if there is a way to create Web GL multi-series with a cartesian chart... 

https://d3fc.io/examples/element-bespoke-chart-layout/
https://bl.ocks.org/ColinEberhardt/a7dc3277e7ab7959781072864e6c9670

**Comment by radames** [comment]
hi @artemiusgreat this seems related to the new breaking feature see details on the [changelog](https://github.com/d3fc/d3fc/blob/master/packages/d3fc-webgl/CHANGELOG.md#features-1)

I suggest you to use version d3fc@15.0.10

**Comment by ColinEberhardt** [comment]
Thanks for raising @artemiusgreat - and @radames thanks for the workaround. I've created a PR with the fix #1620, this will be merged and released shortly

**Comment by ColinEberhardt** [comment]
@artemiusgreat this has been fixed, there will be a new release in a few minutes when the build finishes.

**Comment by artemiusgreat** [comment]
@ColinEberhardt Thank you
