### ISSUE TITLE
d3fc loading latest version for d3-selection breaks d3fc modules

### ISSUE THREAD

**Issue by radames** [d3fc/d3fc#1619]
Hi, this is related to #1606 

I guess d3fc packages are specifying d3 modules dependencies using *"\*"*  thus while using it inside Observable which has a custom import/require system that avoids loading global packages, it would insists in load the latest modules for *d3-selection*, which would break d3fc webgl series.

https://observablehq.com/d/ee0ac610b54ea950@663

Luckily I can override requires inside d3fc bundle 

~~~js
  const r = require.alias({
    d3fc: "d3fc@15.0.10",
    "d3-selection": "d3-selection@1",
    "d3-zoom": "d3-zoom@1",
    "d3-brush": "d3-brush@1",
    "d3-drag": "d3-drag@1",
    "d3-scale": "d3-scale@1"
  });
~~~

here is the working demo https://observablehq.com/@radames/hello-d3fc-webgl

Perhaps in the future it would be a good idea to lock to Minor releases?

@ColinEberhardt solution https://github.com/d3fc/d3fc/issues/1606#issuecomment-683250954 would work great outside Observable

Thanks!

**Comment by ColinEberhardt** [comment]
Thanks for raising @radames - we've fixed the immediate issues in the project examples (#1605 #1606), however, we haven't looked at what needs to be done in order to make this project D3v6 compatible. I doubt there is much to do, but we need to be thorough.

We probably should be more explicit about the D3 version that we are compatible with. Currently it is only expressed as a dev dependency https://github.com/d3fc/d3fc/blob/master/package.json#L50

**Comment by radames** [comment]
Hi @ColinEberhardt thanks for the great work.
Also could you set the Minor releases numbers for peer dependencies? https://github.com/d3fc/d3fc/blob/master/packages/d3fc-chart/package.json#L30-L32, I think the edge cases are when using Observable for example, it has a custom `require()` and automatic imports it from jsdelivr, it also could be a problem if someone is using rollup and rollup-plugin-node-resolve, it would require the dependencies in order to bundle a project and will use the latest incompatible d3 modules. Or I'm not sure if d3fc is es modules compatible,  but I guess the browser would import the dependencies with problems 
 

Thanks

**Comment by chrisprice** [comment]
The V6 changes are now merged so the immediate issue should hopefully be solved.

**Comment by radames** [comment]
the latest version 15.0.19 a7f1db4d1fd44f696c7ead067284851953c18e6c seems to fix the webglDataJoin classed issue! thanks
