### ISSUE TITLE
Unable to make bespoke charts to work with Canvas and Webgl

### ISSUE THREAD

**Issue by artemiusgreat** [d3fc/d3fc#1621]
All bespoke charts that use packages separately seem to be implemented using SVG. 
https://d3fc.io/examples/element-bespoke-chart-layout/

I tried to switch available examples to canvas and webgl 
* replacing `d3fc-svg` in HTML with `d3fc-canvas` 
* replacing `seriesSvgLine` in JS with `seriesCanvasLine` and `seriesWebglLine`

https://codepen.io/artemiusgreat/pen/JjXOxOP

Now, example with canvas raises exception below. The example with webgl doesn't show any errors but doesn't create chart either. 

```
pen.js:30 Uncaught TypeError: fc.seriesCanvaslLine is not a function
    at HTMLElement.<anonymous> (pen.js:30)
    at HTMLElement.<anonymous> (d3.js:1526)
    at draw (d3fc.js:8833)
    at Array.forEach (<anonymous>)
    at redraw (d3fc.js:8840)
    at d3fc.js:8855
```
**Are bespoke charts supposed to be used with SVG only or I just missed something?**

**Comment by chrisprice** [comment]
There's a typo in your code `seriesCanvaslLine` versus `seriesCanvasLine`.

**Comment by artemiusgreat** [comment]
> There's a typo in your code `seriesCanvaslLine` versus `seriesCanvasLine`.

@chrisprice Corrected. The actual error is this one. 

```
d3fc.js:2877 Uncaught TypeError: Cannot read property 'beginPath' of null
    at line (d3fc.js:2877)
    at Selection.selection_call [as call] (d3.js:1140)
    at HTMLElement.<anonymous> (pen.js:37)
    at HTMLElement.<anonymous> (d3.js:1526)
    at draw (d3fc.js:8833)
    at Array.forEach (<anonymous>)
    at redraw (d3fc.js:8840)
    at d3fc.js:8855
```

https://codepen.io/artemiusgreat/pen/JjXOxOP

**Comment by chrisprice** [comment]
The series doesn't extract the context from the canvas, you need to do that explicitly and pass it to the series. See the docs for an example -

https://github.com/d3fc/d3fc/blob/master/packages/d3fc-series/README.md

**Comment by artemiusgreat** [comment]
@chrisprice Thanks. I managed the canvas version to work properly. 
https://codepen.io/artemiusgreat/pen/yLOKJNE

Meanwhile, webgl version looks weird and seems to be using only a part of the canvas, so the chart looks minimized. 
https://codepen.io/artemiusgreat/pen/JjXOxOP

What am I missing?

**Comment by chrisprice** [comment]
You need the attributes on the canvas tag -

https://github.com/d3fc/d3fc/blob/master/examples/series-webgl-line/index.html

This should really be part of a guide...

**Comment by artemiusgreat** [comment]
Thank you. It works now. 
https://codepen.io/artemiusgreat/pen/JjXOxOP
