### ISSUE TITLE
Bespoke chart with SVG scale and Canvas plotter

### ISSUE THREAD

**Issue by artemiusgreat** [d3fc/d3fc#1639]
The example here shows how to create a bespoke chart using only SVG elements. 
https://d3fc.io/examples/element-bespoke-chart-layout/

Then 

* I change the plot area from SVG to Canvas with attribute `use-device-pixel-ratio` 
* check this on retina display with pixel ratio = 2 

Canvas plotter makes everything 2 times smaller than SVG. 
https://codepen.io/artemiusgreat/pen/JjXOxOP

**Question**

How to make both components, Canvas chart and SVG scale, of the same size?
Is there a way to use the same scale for Canvas and SVG even though Canvas pixels are 2 times smaller?

**Comment by chrisprice** [comment]
You can see the approach used by cartesianChart here -
https://github.com/d3fc/d3fc/blob/master/packages/d3fc-chart/src/cartesian.js

**Comment by chrisprice** [comment]
Sorry that was missing the line number - 
https://github.com/d3fc/d3fc/blob/master/packages/d3fc-chart/src/cartesian.js#L107

**Comment by artemiusgreat** [comment]
Thank you. It worked.
