### ISSUE TITLE
D3 zoom example broken on mobile

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#1640]
https://d3fc.io/examples/chart-d3-zoom/#

On mobile, zoom interactions seem to have the wrong center.

**Comment by ColinEberhardt** [comment]
It’s also really quite slow (for me at least) - I’d say around 4fps

**Comment by chrisprice** [comment]
It's something to do with devicePixelRatio, if I override that to 1 in the dev tools it fixes the zooming location.

**Comment by chrisprice** [comment]
It's because `use-device-pixel-ratio` is enabled on the canvas plot-area but not (because it's not applicable) on the svg axes. The working scales (`x`/`y`) have their ranges set based upon the measurements from the axes which are not pre-multiplied by `devicePixelRatio`. Whereas the baseline scales (`x2`/`y2`) have their ranges set based upon the measurements from the plot area which is pre-multipled by `devicePixelRatio`.
