### ISSUE TITLE
How to get chart labels on both  right and left side 

### ISSUE THREAD

**Issue by supriya-somavnshi** [d3fc/d3fc#1642]
I want to give two chart-labels in one line on the top of chart .One label on left side and another on the  right side and both labels has different color and formatting .Please suggest me , how to implement.

Example: I want give S&P 500 on left side and -10.29(- 0.30%) on right side with different color on the same line.

 
![dual chart label](https://user-images.githubusercontent.com/73587174/97431928-66b3e400-18d8-11eb-870d-a7d9129142c1.png)

**Comment by ColinEberhardt** [comment]
This isn’t something that D3FC would support directly, instead I’d recommend using standard HTML layout techniques, flex box for example

**Comment by supriya-somavnshi** [comment]
Thanks for your valuable suggestion . Now it is working with your help .
