### ISSUE TITLE
Scaling or positioning of Canvas and SVG elements on bespoke chart

### ISSUE THREAD

**Issue by artemiusgreat** [d3fc/d3fc#1645]
Retina display. Probably, an outcome of this solution 
https://github.com/d3fc/d3fc/issues/1639 

Overall, scaling works fine except for one minor issue, canvas area is 0.5 pixels smaller than SVG axes. 
As a result, all X ticks look shifted 0.5 px to the right and all Y ticks are shifted 0.5 px to the bottom. 
If I add hardcoded style to adjust position of the canvas area, ticks seems to match lines on the grid. 

```
.plot-area { 
  margin-top: 0.5px;
  margin-left: 0.5px;
}
```
Meanwhile, `cartesian chart` doesn't have this issue, so maybe **there is a better way to make grid lines match ticks positions?** 

https://imgur.com/a/Qb3GQz3
https://codepen.io/artemiusgreat/pen/JjXOxOP

**Comment by chrisprice** [comment]
Sorry, my spot the difference skills are clearly not what they used to be! I think this just comes down to `fc.axis` versus `d3.axis`. I don't think it has anything to do with the `devicePixelRatio` (but I could be wrong!). 

If you swap over to the latest version of d3 and use the following JS it works -
```js
const sample = d => ({ x: d / 3, y: Math.sin(d / 3) });
const data = d3.range(50).map(sample);
const xScale = d3.scaleLinear();
const yScale = d3.scaleLinear();
const chart = d3.select('#chart');
const ctx = document
  .querySelector('.plot-area canvas')
  .getContext('2d');

const line = fc
  .seriesCanvasLine()
  .xScale(xScale)
  .yScale(yScale)
  .context(ctx);

const gridline = fc
  .annotationCanvasGridline()
  .xScale(xScale)
  .yScale(yScale)
  .context(ctx);

const gridlineSvg = fc
  .annotationSvgGridline()
  .xScale(xScale)
  .yScale(yScale);

const multi = fc
  .seriesCanvasMulti()
  .series([gridline, line])
  .xScale(xScale)
  .yScale(yScale)
  .context(ctx);

const xExtent = fc.extentLinear().accessors([d => d.x]);
const yExtent = fc.extentLinear().accessors([d => d.y]);
const plot = chart.select('.plot-area').node();

const chartContainer = chart.on('draw', () => {
  ctx.scale(window.devicePixelRatio, window.devicePixelRatio);
  xScale.range([0, plot.clientWidth]);
  yScale.range([plot.clientHeight, 0]);
  xScale.domain(xExtent(data));
  yScale.domain(yExtent(data));
  multi(data);
})

chart.select('.x-axis-bottom').on('draw', ({detail}) => {
    const xAxis = fc.axisBottom(xScale);
    d3.select(detail.child).call(xAxis);
});

chart.select('.y-axis-right').on('draw', ({detail}) => {
    const yAxis = fc.axisRight(yScale);
    d3.select(detail.child).call(yAxis);
});

chartContainer.node().requestRedraw();
```
And you can see it in action here -
![image](https://user-images.githubusercontent.com/433457/98443237-fee47100-2101-11eb-91aa-b71b8aaa96da.png)

I haven't done any further digging to establish why this fixes it. I'd be interested to know if you find out.

**Comment by artemiusgreat** [comment]
Works like a charm. Thank you :)
