### ISSUE TITLE
Inverse crosshair coordinates to scale values on ordinal scale

### ISSUE THREAD

**Issue by artemiusgreat** [d3fc/d3fc#1649]
Trying to show crosshair scale values in a tooltip feeding coordinates to `invert` method. It works fine when the scale has type `scaleLinear`.
https://codepen.io/artemiusgreat/pen/xxVQEbW 

With ordinal scales `scalePoint`, I'm getting an error saying that `scalePoint` doesn't have method `invert`. 
https://github.com/d3fc/d3fc/issues/1638

There are a couple of suggestions of how this could be approximated in D3. 
https://stackoverflow.com/questions/20758373/inversion-with-ordinal-scale

Meanwhile, maybe there is a built-in solution for this in D3FC?

**Comment by chrisprice** [comment]
Non continuous scales are tricky to use, is avoid them if possible. Have you considered using a linear scale with the index of the datum as the X value? It should give you a similar effect as long as you use the tick format method on the axis to lookup the right timestamp in the data.

**Comment by artemiusgreat** [comment]
Great idea. This is exactly what I needed. Thanks. 
https://codepen.io/artemiusgreat/pen/BazKEjw
