### ISSUE TITLE
Question about extending plotting methods

### ISSUE THREAD

**Issue by JoeCarlson** [d3fc/d3fc#1651]
Hello and thanks for this great project. One question I had was how to extend the plotting options. I wanted to try out is creating a violin plot component (essentially, a box plot with the box replaced with a sideways histogram). I tried following along with the boxplot series code but quickly ran into issues since it uses methods (i.e. xyBase) that are not exported. (I must admit I don't have a lot of experience with extending javascript modules; let me know if there is something I'm missing.)

Other than forking the repo, do you have suggestions on how to write new a new plot series which can reuse components od d3fc?

**Comment by artemiusgreat** [comment]
Have you tried using `decorate` method? 
It allows you to get access to underlying context where the `series` will be drawn, e.g. `canvas`. 
Given this, you will have access to HTML canvas and the coordinates of the current data point in the series, so you can draw anything on top of it. 
Check this answer on SO. 
https://github.com/d3fc/d3fc/issues/1635
It shows how to draw custom symbols on top of the candle. 
In your case, you could draw multiple horizontal `rect` for each vertical candle or bar.

**Comment by ColinEberhardt** [comment]
Violin plots look similar to market profile charts - here's a blog post where I described how to create a new market profile series using D3FC:

https://blog.scottlogic.com/2017/08/23/market-profile.html

![image](https://user-images.githubusercontent.com/1098110/99081113-2fbd1e00-25ba-11eb-9e25-ac110a4a33ae.png)

I think you can use a similar approach, where each 'violin' is itself rendered on a composite scale as described above.

**Comment by JoeCarlson** [comment]
Thank you for this. It looks very useful. I'll try it out.

**Comment by JoeCarlson** [comment]
Thanks for the comment. I tried the bar plotting and saw that it was very sluggish. But doing it all with seriesSvgArea and seriesSvgRepeat was the ticket. Let me know if you'd like to see my example.

**Comment by ColinEberhardt** [comment]
Sure, it would be great to see what you’ve created.

**Comment by JoeCarlson** [comment]
violin plots are described here https://www.tandfonline.com/doi/abs/10.1080/00031305.1998.10480559

violin.htnl and violin.js in this zip file.
[violin.zip](https://github.com/d3fc/d3fc/files/5556693/violin.zip)

By way of background, what we're using them for is a display of gene expression as measured from 110K single cells of plant roots. I stumbled on your rendering-one-million-points-with-d3 and used that as my starting point. The violin plots are summaries of groups of cells along different time points in their development state.

**Comment by JoeCarlson** [comment]
I loaded it on gist. https://bl.ocks.org/JoeCarlson/a4cb2dbb2abe3a9ba2e795afa2004d02

**Comment by ColinEberhardt** [comment]
Great job, thanks for sharing - I might add this to the examples on the D3FC website
