### ISSUE TITLE
ERROR TypeError: container.selection is not a function when implementing d3fc chart in Angular component

### ISSUE THREAD

**Issue by alexdbugging** [d3fc/d3fc#1653]
I've been trying to implement a d3fc chart in a Angular app using Angular components. I've used the test implementation of simple-chart to see if my implementation works, however I keep running into the same error message:

```
ERROR TypeError: container.selection is not a function
    at dataJoin (d3fc.js:2772)
    at HTMLDivElement.<anonymous> (d3fc.js:10141)
    at Selection.each (each.js:5)
    at cartesian (d3fc.js:10140)
    at Selection.call (call.js:4)
    at D3fcWebglGraphComponent.ngOnInit (d3fc-webgl-graph.component.ts:49)
    at checkAndUpdateDirectiveInline (core.js:33625)
    at checkAndUpdateNodeInline (core.js:46733)
    at checkAndUpdateNode (core.js:46672)
    at prodCheckAndUpdateNode (core.js:47530)
```

I've been stuck with this error for a while now and feel like I've exhausted all the possible help resources available. Do you have any suggestions for me?

Here's my implementation:
**component.ts**
```
import {
    Component,
    ElementRef,
    OnInit,
    ViewChild,
    SimpleChanges
} from '@angular/core';

import * as d3 from 'd3';
import * as fc from 'd3fc';

@Component({
    selector: 'app-d3fc-webgl-graph',
    templateUrl: './d3fc-webgl-graph.component.html',
    styleUrls: ['./d3fc-webgl-graph.component.scss']
})
export class D3fcWebglGraphComponent implements OnInit {
    @ViewChild('chart') chartContainer: ElementRef;

    constructor() {}

    ngOnInit(): void {
        const data = fc.randomFinancial()(50);

        const yExtent = fc.extentLinear().accessors([d => d.high, d => d.low]);

        const xExtent = fc.extentDate().accessors([d => d.date]);

        const gridlines = fc.annotationSvgGridline();
        const candlestick = fc.seriesSvgCandlestick();
        const multi = fc.seriesSvgMulti().series([gridlines, candlestick]);

        const chart = fc
            .chartCartesian(d3.scaleTime(), d3.scaleLinear())
            .yDomain(yExtent(data))
            .xDomain(xExtent(data))
            .svgPlotArea(multi);

        d3.select(this.chartContainer.nativeElement)
            .datum(data)
            .call(chart);
    }
}
```

**component.html**
```
<h1>D3FC chart test</h1>
<div class="chart-container">
    <div id="chart" #chart></div>
</div>
```

**Comment by alexdbugging** [comment]
UPDATE: I managed to solve the problem by downgrading my d3 library to 5.14.2 and d3fc to 14.1.0.

**Comment by chrisprice** [comment]
That would explain it. The latest version of d3fc requires the latest version of d3 v6.

The specific problem you're seeing is related to `c0175ae` as seen here -
https://github.com/d3fc/d3fc/compare/@d3fc/d3fc-data-join@6.0.2...@d3fc/d3fc-data-join@6.0.3

**Comment by alexdbugging** [comment]
I tried updating both packages. I am using d3fc v. 15.1.1 and d3 v. 6.2.0, however the problem still persists with the implementation I provided.

**Comment by chrisprice** [comment]
Seems to work fine for me - 

https://codesandbox.io/s/festive-mcnulty-ef1io?fontsize=14&hidenavigation=1&theme=dark

I assume you're somehow pulling in an older version of d3 or multiple versions somehow. If you can you create an equivalent codesandbox example demonstrating your problem, I might be able to help further.

**Comment by alexdbugging** [comment]
Seems to work fine for me as well when I move my implementation to CodeSandbox. However I am facing a new problem of plotting a Webgl stacked bar chart in a cartesian chart and adding a navigator chart to that as well. I have the navigator chart working as well as the x and y scales showing the correct values, but I am really confused on how to render the Webgl stacked bar data in the cartesian chart above. If you could guide me on how to plot the stacked bar series that would be really appreciated.

Here's a link to my implementation:
https://codesandbox.io/s/boring-cori-o4ypr?file=/src/app/d3fc-webgl-graph.component.ts

I'm trying to achieve something along the likes of this:
(I know the values of the chart and navigator chart don't match, but I hope you get the idea)
![graph_ref](https://user-images.githubusercontent.com/73697502/100097708-39b60b00-2e5d-11eb-9507-790232ba54a4.PNG)

**Comment by alexdbugging** [comment]
After some further investigation it seems that the d3fc-group element is not being declared in the div I've assigned the chart to. Is there a way to ensure that it gets set, or do you know what the cause of it not getting set could be?

**Comment by alexdbugging** [comment]
I managed to figure it out - I had a version of AmCharts that kept pulling an old version of d3-selection (1.4.1) and I required d3-selection 2.0.0 to insert d3fc-group into my div. I fixed the error by uninstalling AmCharts from my project.
