### ISSUE TITLE
Snapshot svg chart

### ISSUE THREAD

**Issue by Serg65s** [d3fc/d3fc#1662]
How to take a snapshot of the working area of ​​an svg chart along with the axes saving in png or svg? I use saveSvgAsPng but don't understand how to include axes in the general svg area.

**Comment by ColinEberhardt** [comment]
Hi - this isn't something we'd expect to support directly. D3FC creates conventional SVG / Canvas objects within the DOM, so I'd expect a 'standard' approach would work.
