### ISSUE TITLE
Question about the usage of d3fc-zoom and a streaming candlestick chart

### ISSUE THREAD

**Issue by hetsch** [d3fc/d3fc#1670]
Hi,

first, thank you for your awesome libraries! 

I'm currently playing around with the zoom library and a streaming chart. One of my problems is, that everytime a new value comes in from the stream, the chart (eg. scale) looses it's zoom transformation and jumps back to the base scale.

Here is an example what I mean: https://codepen.io/bennybunny/pen/mdOMzaz

Any ideas are highly appreciated. Thank you!

**Comment by chrisprice** [comment]
That's a consequence of this line -
```chart.yDomain(yExtent(data.series)).xDomain(xExtent(data.series))```

The zoom interactions work by updating the x/y scale domains. The line above is explicitly setting the domain when the new value is added, overriding any zoom interactions derived value.

What behaviour did you want to see when the new point is added?

**Comment by hetsch** [comment]
Hi Chris, thank you for your quick response. What I like to have is the representation of the new data with new candles with the defined extent but preserving the actual zoomed scale.

**Comment by chrisprice** [comment]
Hmm I'm not sure what you mean by base scale. There's no difference between the defined extent (assuming you mean the scale domains) and the actual zoomed scale when you're using d3fc-zoom, the zoom component directly manipulates the scale domains.

**Comment by hetsch** [comment]
Hi Chris,

sorry for the late response. There was actually nothing to understand right because I got it totally wrong :)

What I actually want to achieve is building a streaming chart that

- receives an update of the data every - let's say - one second
- should store all the data for an infinite amount of time (and execute do `data.series.shift()`  as in my previous example)
- should only show a fraction of the data (~100 candles) in the chart's viewport
- should display the whole data if the user zooms out - but only to an extent that zooming out stops once the view of the whole data is smaller than the viewport.
- should only allow zooming while there is a candle left to show on the viewport

This is roughly what I like to achieve. I thought I was much closer to the solution than I am, actually. Any inputs are more than welcome.

**Comment by chrisprice** [comment]
It sounds like you just need a bit of logic in your zoom handler to check the updated domains of the scales and constrain them if appropriate, by setting them to the constrained value.

**Comment by hetsch** [comment]
I totally forgot to close this issue. Thank you for your help!
