### ISSUE TITLE
d3fc Rectangle Zoom on Canvas

### ISSUE THREAD

**Issue by etechprathmesh** [d3fc/d3fc#1672]
Hi,

Could you please send me example of Zoom on Canvas. I want to select rectangle area of selection using Mouse down / Mouse Up.

**Same as following example, But instead of SVG, I want to use same functionality on Canvas.
https://d3fc.io/examples/brush-zoom/**

Regards,

Prathmesh

**Comment by ColinEberhardt** [comment]
Closing as per comment on #1669 - you're asking questions that are relatively easy to deduce from the documentation. Also, continually messaging the maintainers of this project is not the right way to get support!

https://twitter.com/prathamesh19731/status/1363825278980558849
https://twitter.com/prathamesh19731/status/1362282481534181376
https://twitter.com/prathamesh19731/status/1362282080508383236
