### ISSUE TITLE
has anyone ever built a good chart with this library?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [d3fc/d3fc#1684]
Anyone used this in production? 
No single example has good UI controls and feel. All feel really incomplete. Even the complex financial chart has no zoom & pan. Most charting libraries are really ugly from ground up ( see https://www.arction.com an overpriced mess ). 

This one has very obscure customization options, no documentation exists. 

#1  Streaming Candle Chart 

https://d3fc.io/examples/streaming-chart/

this example isn't really helpful for people who want to update intrabar values.

#2 https://d3fc.io/examples/series-webgl-line/
this example, once you click on the chart you can never go back.

**Comment by stereokai** [comment]
@hp8wvvvgnj6asjm7 did you make any progress?
