### ISSUE TITLE
Irregular shape of heat map rectangles 

### ISSUE THREAD

**Issue by supriya-somavnshi** [d3fc/d3fc#1691]
I am using react-vis for heat map. I am trying to plot rectangle shape of Heat map but irregular shapes of rectangle are showing in heat map.  Please suggest me the reason of this issue.

Please find my code attached .

![image](https://user-images.githubusercontent.com/73587174/113294480-aa41cc80-9314-11eb-95be-51d82529c34b.png)
[Heat Map.zip](https://github.com/d3fc/d3fc/files/6243520/Heat.Map.zip)

**Comment by ColinEberhardt** [comment]
Hi @supriya-somavnshi  from a quick glance at your code it looks like you use react-vis to render this heatmap. I'd recommend opening an issue here https://github.com/uber/react-vis
