### ISSUE TITLE
selectionOrTransition.selection is not a function

### ISSUE THREAD

**Issue by krngd2** [d3fc/d3fc#1699]
I am trying to create Auto rotating Axis labels in typescript 
```
import { axisLabelRotate, axisOrdinalBottom } from "@d3fc/d3fc-axis"; 

this.xAxisGenerator = axisLabelRotate(axisOrdinalBottom(this.xScale))

this.svg.append('g')
                .classed('xAxis', true)
                .call( this.xAxisGenerator )
```
I am getting this error 

    selectionOrTransition.selection is not a function
    at isTransition (<anonymous>:2466:32)
    at axis (<anonymous>:1910:85)
    at axis (<anonymous>:2331:5)
    at axisLabelRotate (<anonymous>:2236:5)

**Comment by chrisprice** [comment]
Can you confirm which version of d3 you are using? I would expect to get this error with older versions of d3.

**Comment by krngd2** [comment]
Hello @chrisprice, I am using d3js v5.12.0

**Comment by chrisprice** [comment]
The above functionality requires v6 minimum

**Comment by krngd2** [comment]
It worked after upgrading. Thanks
