### ISSUE TITLE
Getting click location on scatter plot

### ISSUE THREAD

**Issue by kdutia** [d3fc/d3fc#1704]
I'm trying to extend the [Hathi Trust visualisation](https://colineberhardt.github.io/d3fc-webgl-hathi-explorer/#), by making points clickable so extra information can be shown in a sidebar (like [this example](http://zinenet.work/)). 

I'm trying to do this using `d3.mouse` like this, selecting the HTML element with the plot area in. No clicks are registered though and the svg isn't being appended.

``` js
// at the bottom of index.js
var svg = d3.select("d3fc-svg.plot-area").append('svg')
svg.on("click", () => {
  console.log("click!")
  console.log(d3.mouse(svg.node()))
})
```

Is there a way to track click events and locations using d3fc, like this or otherwise?

Thanks!

**Comment by ColinEberhardt** [comment]
The Hathi Trust Visualisation already has most of the code you need to achieve that. The [d3fc pointer](https://github.com/d3fc/d3fc/blob/master/packages/d3fc-pointer/README.md) component is used to raise an event with x/y location when the users clicks on the plot area:

https://github.com/ColinEberhardt/d3fc-webgl-hathi-explorer/blob/master/index.js#L152

The event handler uses the x & y scales to convert from the screen coordinates to the visualisation's coordinate system:

https://github.com/ColinEberhardt/d3fc-webgl-hathi-explorer/blob/master/index.js#L110-L111

Following that, a D3 quadtree is used to locate the closest datapoint (within a 20 pixel radius)

You should be able to add your 'sidebar' logic just here:

https://github.com/ColinEberhardt/d3fc-webgl-hathi-explorer/blob/master/index.js#L117

**Comment by kdutia** [comment]
Thanks for the swift reply. 

d3fc pointer only tracks mouse position in that example I think. How do I track a click event?

**Comment by kdutia** [comment]
An update: I've managed to register click events by changing the source of `d3fc-pointer/src/pointer.js` as below. However, it now seems like pointer events are not registered, i.e. the `rebind` method overwrites the work done for pointEvents with clickEvents.

What's the best way to proceed from here? Is there a way to dispatch both point and click events, or should I make a `clicker.js` in my d3fc fork which is completely separate from pointer.js?

Happy to add these changes to a PR once they're tidied.

``` js
import { dispatch } from 'd3-dispatch';
import { pointer } from 'd3-selection';
import { rebind } from '@d3fc/d3fc-rebind';

export default () => {
    const pointEvent = dispatch('point');
    // added line below
    const clickEvent = dispatch('click');

    function mousemove(event) {
        const point = pointer(event);
        pointEvent.call('point', this, [{ x: point[0], y: point[1] }]);
    }
    
    // added this method
    function mouseclick(event) {
        const point = pointer(event);
        clickEvent.call('click', this, [{ x: point[0], y: point[1] }]);
    }

    function mouseleave() {
        void pointEvent.call('point', this, []);
    }

    const instance = (selection) => {
        selection
            .on('mouseenter.pointer', mousemove)
            .on('mousemove.pointer', mousemove)
            .on('mouseleave.pointer', mouseleave)
            // added line below
            .on('click.pointer', mouseclick);

    };

    rebind(instance, pointEvent, 'on');
    // added line below
    rebind(instance, clickEvent, 'on');

    return instance;
};


```

**Comment by ColinEberhardt** [comment]
Looks like you are getting close - I was going to recommend extending the `pointer` component.

The issue is here:

~~~
    rebind(instance, pointEvent, 'on');
    // added line below
    rebind(instance, clickEvent, 'on');
~~~

Rebind takes a property of one object and rebinds (copies) it to another. In this case you are rebinding the `on` property of two objects to the `pointer` component. This results in a naming collision.

Rebind allows you to change the name of the re-bound property. Take a look at cartersian chart where two axis components are rebound, with different prefixes:

https://github.com/d3fc/d3fc/blob/master/packages/d3fc-chart/src/cartesian.js#L176

**Comment by kdutia** [comment]
I ended up [creating a new `clicker` component](https://github.com/kdutia/d3fc/commit/f683cf3f7e70f3fc88869489a4ddf0a1b135efde#diff-a583ec383953418a7580d4415f51a29caf25c0410ef42aca8ac975a040bc537c) on Friday which works (ignore the rest of the commit, it's mostly just files I copied over from the pointer).

I'll try extending the `pointer` component today or tomorrow and hopefully there will be a PR coming your way this week.

**Comment by kdutia** [comment]
Just looking at this in more detail. From what I can tell the following code would no longer work if we changed the name of the rebound property like in your suggestion, as we'd have to override the `on` method for one or both of `"point"` or `"click"`. Is this correct?

``` js
const pointer = fc.pointer()
.on("point", ([coord]) => {
  // do something with point 
}
.on("click", ([coord]) => {
  // do something with click
}
```

If so I'd suggest that separating out `pointer` and `clicker` and keeping the `on` method for both might be a cleaner solution, especially for someone familiar with `d3` but not `d3fc`.

``` js
const pointer = fc.pointer()
.on("point", ([coord]) => {
  // do something with point 
}

const clicker = fc.clicker()
.on("click" ([coord]) => {
  // do something with click 
}
```

Sorry if I've got the wrong end of the stick here, Javascript isn't my main language so it's taking me a bit of time to get up to speed. If I'm wrong it'd be useful to understand a bit more how the `prefix` method is applied - I understand that it's a curried function and what it does to text, but can't quite figure out how it's used in the `cartesian` example.

**Comment by kdutia** [comment]
Hi @ColinEberhardt. I'm just coming back to this now - I left it having made a new `d3fc-clicker` component which successfully tracks click events. The [commit is here](https://github.com/kdutia/d3fc/commit/f683cf3f7e70f3fc88869489a4ddf0a1b135efde). It currently contains lots of placeholder documentation as I copied the `d3fc-pointer` folder as a starter, but the important part is in `packages/d3fc-clicker/src/clicker.js`.

``` js
import { dispatch } from 'd3-dispatch';
import { pointer } from 'd3-selection';
import { rebind } from '@d3fc/d3fc-rebind';

export default () => {
    const clickEvent = dispatch('click');

    function mouseclick(event) {
        const point = pointer(event);
        clickEvent.call('click', this, [{ x: point[0], y: point[1] }]);
    }

    const instance = (selection) => {
        selection
            .on('click.pointer', mouseclick);

    };

    rebind(instance, clickEvent, 'on');

    return instance;
};
``` 

**If I were to tidy up the rest of the files in this commit and make a PR back to the `d3fc` repo, do you think it would be accepted?** Would I need to touch anything else that's not in the files in the above commit?

Asking because otherwise I'll need to look into hosting my fork in a private npm registry, and it seems like the click component is a useful addition to the main version of `d3fc`. (I'm making a demo of the UMAP projection of knowledge graph embeddings [for the Science Museum and the V&A](https://www.sciencemuseumgroup.org.uk/project/heritage-connector/)).

Thanks

**Comment by chrisprice** [comment]
Hi @kdutia, sounds like an interesting project! 

Whilst we definitely could consider the best way of including similar functionality, I'm not too keen on continuing down the route of adding behaviours to the public API without understanding how other interactions would be supported. It wouldn't be ideal to have to add a new component for each interaction type e.g. clicker, doubleClicker, rightClicker, etc.. [Pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events) are probably a good abstraction we could build on, but I've not done any research. Or more likely, there's an even more elegant way I've not considered. However...

My expectation would be that adding a component such as the above to your code should be an easy option. I certainly wouldn't expect you'd need to fork and maintain your own version of this whole repository! As an example of how it can be done, `bollingerBands` in the [Idempotent Streaming Chart](https://github.com/d3fc/d3fc/blob/master/examples/idempotent-streaming-chart/index.js#L47) example is a custom component much like your clicker. If it's not obvious how to appropriate the example for your project, feel free to share what you've got and we can help you out.

**Comment by kdutia** [comment]
Thanks @chrisprice, agreed that pointer events would be a good abstraction to build on. For now I've just [packaged a bundled version of my fork alongside the demo](https://github.com/TheScienceMuseum/heritage-connector-demos/tree/main/3_visualisation). 

Later this month I'll be looking into adding a double click interaction to isolate points with a specific label, so I'll look into making a new custom component within the demo at that point. Happy to close this issue if you are, thanks for all your help 🙂

**Comment by abitrolly** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events look too low level, and custom `click` event would solve 80%+ of the cases when people need to make the chart responsive to clicks.

`d3.dispatch` allows to define multiple events at once, so it looks like this should work.
```js
import { dispatch } from 'd3-dispatch';
import { pointer } from 'd3-selection';
import { rebind } from '@d3fc/d3fc-rebind';

export default () => {
    // modified the line below
    const pointerEvent = dispatch('point', 'click');

    function mousemove(event) {
        const point = pointer(event);
        pointerEvent.call('point', this, [{ x: point[0], y: point[1] }]);
    }
    
    // added this method
    function mouseclick(event) {
        const point = pointer(event);
        pointerEvent.call('click', this, [{ x: point[0], y: point[1] }]);
    }

    function mouseleave() {
        void pointerEvent.call('point', this, []);
    }

    const instance = (selection) => {
        selection
            .on('mouseenter.pointer', mousemove)
            .on('mousemove.pointer', mousemove)
            .on('mouseleave.pointer', mouseleave)
            // added line below
            .on('click.pointer', mouseclick);

    };

    // modified the line below
    rebind(instance, pointerEvent, 'on');

    return instance;
};
```
