### ISSUE TITLE
how to get sub-series title in series SVG Grouped ? 

### ISSUE THREAD

**Issue by sandeep-kr-kgp** [d3fc/d3fc#1706]
https://github.com/d3fc/d3fc/blob/a1b25d23ceaba0531dd77af90828b550bcf53eea/examples/series-svg-grouped/index.js#L1-L10

https://github.com/d3fc/d3fc/blob/a1b25d23ceaba0531dd77af90828b550bcf53eea/examples/series-svg-grouped/index.js#L64-L76

.decorate((sel, _, index) => {
        sel.enter()
            .select('path')
            .attr('fill', () => color(index))
            .on("mouseover", function(event,d){
            console.log(d);
            });
    });

getting d as ['AL', 310, data{...}],  ['AL', 552, data{...}]..how do I get the sub-heading i.e. 'Under 5 years' on mouseover events. Need it for tooltip purposes

**Comment by ColinEberhardt** [comment]
It looks like this is a piece of information that the group component does not include in its transformation. If you look at the implementation of group:

https://github.com/d3fc/d3fc/blob/master/packages/d3fc-group/src/group.js#L9-L21

You can see that the transformation is effectively the following:

~~~
const series = Object.keys(data[0])
            .filter(k => k !== "State")
            .map((k) => {
                const values = data.filter(row => row[k])
                    .map((row) => {
                        const cell = [row["State"], row[k]];
                        cell.data = row;
                        return cell;
                    });
                values.key = k;
                return values;
            });
~~~

All that needs to be done is update the value of `cell` above, to add the required group value:

~~~
const series = Object.keys(data[0])
            .filter(k => k !== "State")
            .map((k) => {
                const values = data.filter(row => row[k])
                    .map((row) => {
                        const cell = [row["State"], row[k], k];
//                                                          ^-- here
                        cell.data = row;
                        return cell;
                    });
                values.key = k;
                return values;
            });
~~~

As a result, in your above code `d` now container the group name:

![image](https://user-images.githubusercontent.com/1098110/124590096-aca34d80-de52-11eb-8e4c-7bd9cc7164d6.png)

**Comment by sandeep-kr-kgp** [comment]
Thanks.
