### ISSUE TITLE
[Question] How to create a graphic with two y-axis ? 

### ISSUE THREAD

**Issue by ibensalah** [d3fc/d3fc#1707]
Hello, 

I would like to create a chart with two axis. I want to plot one of my dataset using the right axis as the y-axis and the other with the left axis as the y-axis. 

I have found a working example in d3.js "https://bl.ocks.org/d3noob/e34791a32a54e015f57de". I also have found this example for d3fc "https://d3fc.io/examples/chart-cartesian-second-axis/" but I can't plot a dataset using the right axis as the y-axis. 

Can you help me please ?

**Comment by chrisprice** [comment]
It looks like the behaviour you are looking for was mistakenly missing from the example. See the linked PR for a quick and somewhat hacky way to do it. A cleaner way would be to wrap the `area` component in an adapter which did not propagate the `yScale` to the `area` component e.g. -

```js
const scaleFixer = (wrappedInstance, yScale) => {
  const instance = (...args) => wrappedInstance(...args);
  instance.yScale = (...args) => {
    if (args.length) {
      wrappedInstance.yScale(yScale);
      return wrappedInstance;
    }
    return yScale;
  }
  fc.rebindAll(instance, wrappedInstance, fc.exclude('yScale'));
}
```
