### ISSUE TITLE
Synchronizing 2 separate zoom behaviors and pointer

### ISSUE THREAD

**Issue by Serg65s** [d3fc/d3fc#1708]
Need help!

[]https://codepen.io/chu123/pen/ExmmgPK)

There is a working simple code, but unfortunately when calling 

**d3.select ('# zoom-chart .plot-area').call (pointer);**

it stops working correctly if we change zoom for the y-axis and then move the graph to the .plot-area, the chart is "jump" and the chart scale is returned to the previous value

**Comment by chrisprice** [comment]
d3-zoom is very hard to work with. Have you tried using d3fc-zoom as in this [example](https://d3fc.io/examples/chart-d3fc-zoom/)?

For a more in-depth discussion of why I think it's easier to use see this [blog post](https://blog.scottlogic.com/2020/10/22/fixing-the-d3-zoom-api.html)

**Comment by chrisprice** [comment]
Probably worth noting you're on older versions of both d3 and d3fc.

**Comment by Serg65s** [comment]
It works. But there's a problem. I need to display the values ​​of the last close and crosshair. These output values ​​are overlapped by the axes. If you display them on top of the axes (.... sel.enter (). Append ("d3fc-svg"). Style ("grid-column", 4) .style ("grid-row", 3) .style (" width "," 45px "). on (" draw.callout ....) something like this, then the focus for zoom is lost. If you get focus using d3.select, then the chart jumps along the y-axis

https://codepen.io/chu123/pen/ExmmgPK

**Comment by Serg65s** [comment]
Solved
