### ISSUE TITLE
Resize points in seriesWebglPoint?

### ISSUE THREAD

**Issue by halilkerimi** [d3fc/d3fc#1724]
Is there e way to automatically zoom points in seriesWebglPoint when scrolling?

I am trying to create a heat map using seriesWebglPoint, but when zooming in the chart, I will get small dots  (initial size)

**Comment by chrisprice** [comment]
Is this an example of the behaviour you're after? https://chrisprice.io/d3fc-webgl-hathi-explorer/

If so, here's the code which is doing it https://github.com/chrisprice/d3fc-webgl-hathi-explorer/blob/master/index.js#L276

It's using a customised point series but you should be able to make it work with the out of the box point series with minimal changes.

**Comment by halilkerimi** [comment]
That's very helpful,
Thanks a lot!
