### ISSUE TITLE
Question: Toggling WebGL Series on Button Click

### ISSUE THREAD

**Issue by johncardiologs** [d3fc/d3fc#1737]
Hi,
The title says it all. I'm working on a scatterplot that uses millions of data points, so I'm resorting to `fc.seriesWebglPoint()` which so far has been great. I have multiple point series in my graph which I'm passing to `seriesWebglMulti()`.  I'm wondering if there's a way to make it such that when a button is clicked, a layer of points changes color. Can one somehow select the button from `decorate` and detect any events, then re-render that series with a different color? Or what is the best way to add this type of interactivity, if possible?

On another note, is there a discord/slack group that harbors a community for this tool? D3FC is a handy tool, and having a place for newcomers (like myself) to ask questions would be great IMO.
Thanks.

**Comment by ColinEberhardt** [comment]
Hi @johncardiologs - the standard pattern for D3FC is to create a render / redraw function that re-renders the entire chart whenever anything changes. Here's an example:

https://github.com/ColinEberhardt/d3fc-webgl-hathi-explorer/blob/master/index.js#L157-L159

This relies on the efficient data-join logic within both D3 and D3FC to ensure that it only updates what is needed on each re-render. Also, as a result, your code is nice and simple - you don't have to determine which parts of you chart need re-rendering on each change, just re-render the lot!

Regarding your specific question:

> Can one somehow select the button from decorate and detect any events, then re-render that series with a different color? 

Yes, that is exactly what I would do.

Handle the button client click event, change your variable that you want to toggle, and invoke your `render` function. Then ensure that your `decorate` function uses this variable to select the required color.

Here's an example that does just that:

https://github.com/ColinEberhardt/d3fc-webgl-hathi-explorer/blob/master/index.js#L43-L59

**Comment by johncardiologs** [comment]
Hi @ColinEberhardt,

Thanks for this! That is indeed the logic I ended up going after and it did work out for me.

One feature that I've been having issues with however is changing the `size` attribute of a point series, in response to an event (button click). My guess is this doesn't get updated on a redraw somehow, because that size logic isn't happening inside of `decorate` (rather it's just chained to my series declaration currently). Curious to hear if there are ways to decorate the shape and/or size of points in a webgl series, and have these be updated dynamically (on a `redraw()`).

Thank you!

**Comment by chrisprice** [comment]
It is possible to force recalculation of the size but doing so will cause
all of the data to be retransferred to the GPU so isn't an a great solution
if you're only changing a small number of point sizes.

> equals - This property is an equality function to control whether any
pre-processing of the data is required i.e. is the data being rendered
equal to the rendered on the previous call. If the data is considered
equal, then the value accessors will not be invoked and the data previously
loaded into the GPU will be re-used.

A cheap and easy way to achieve a similar effect is to render an SVG or
canvas series containing only the point of interest, over the top. Here's
an example of doing something similar-

https://d3fc.io/examples/webgl-with-svg-overlay/

**Comment by johncardiologs** [comment]
Understood. Thanks so much for these thorough answers, Colin and Chris!
