### ISSUE TITLE
How to temporarily disable[enable] the zooming in d3fc - zoom?

### ISSUE THREAD

**Issue by Serg65s** [d3fc/d3fc#1739]
=selection.call(fc.zoom().on("zoom", render), xScale, yScale)
A [d3.zoom](https://github.com/d3/d3-zoom#zoom) component is used internally to bind the necessary event listeners. Therefore you can unbind the behaviour as follows:

selection.on(".zoom", null);
=
selection.on(".zoom", null);  it doesn't work for some reason if it is within the if condition

**Comment by ColinEberhardt** [comment]
Hi - I'm afraid you're going to have to add a bit more information to this issue!
