### ISSUE TITLE
Building D3FC on Node v.18.2.0 fails

### ISSUE THREAD

**Issue by johncardiologs** [d3fc/d3fc#1743]
See error logs after cloning the repository and running `npm ci` with nvm node version `18.2.0`: https://pastebin.com/zACm9jK4

I switched to node version `11.15.0` which worked, but thought I'd make this issue to ask if this was known. I'm hoping to help contribute some TypeScript types to this project, so any pointers on where to get started are welcome! I've already identified the following PRs / issues and plan to go off of these:

- https://github.com/d3fc/d3fc/issues/590
- https://github.com/d3fc/d3fc/pull/1697 (though it seems there no longer is a central `d3fc.d.ts` file -- I'll simply look for `.d.ts` file at each package root)
- https://github.com/d3fc/d3fc/pull/1698
- https://github.com/d3fc/d3fc/pull/1702

Thanks.

**Comment by murcikan-scottlogic** [comment]
Hi @johncardiologs, the [LTS version 16.15.1](https://nodejs.org/en/download/) should work just fine though there may be some other dependencies apart from node that are required (C++ compiler and maybe others). The main .d.ts placeholder file can be found [here](https://github.com/d3fc/d3fc/blob/master/packages/d3fc/index.d.ts)

**Comment by johncardiologs** [comment]
Understood, I'll use 16.5.1 for development from here on out then.
Just added my pointer type contribution to the main .d.ts file in my [PR](https://github.com/d3fc/d3fc/pull/1751)! Doesn't seem like I can request reviewers.
