### ISSUE TITLE
Is a node version bump in the works?

### ISSUE THREAD

**Issue by Kevin-Prichard** [d3fc/d3fc#1778]
Hello,

Experienced d3 user here, new to d3fc, excited to learn this style of componentisation and apply it to my work.

Following the steps in README.md, whilst in master d3fc@15.2.6, and `nvm` set to --lts (currently node v18.12.1), just about every shell step ended up at the same error, where gyp errors out after a 404 fetching a compatible release of canvas ([node-canvas-prebuilt](https://github.com/node-gfx/node-canvas-prebuilt/releases)) @v2.6.1.

That's the last version on their repo; they have release packages only up to node 15.14.0 (node module [version v88](https://nodejs.org/en/download/releases/#ref-1)), so I `nvm`ed that node version, and now everything works.

Is my assumption correct, then - are contributors to run the bundle at v15.14.0?  Should this be mentioned in README.md -- should I make a PR?

Every project's package.json gets out-of-date rather faster than we'd like.  This project has 66 "high" vulnerabilities.  Is there value for this project in catching up to recent node & npm package versions, is it worth my attempting?

**Comment by bethpritchard** [comment]
We are now using Node version 20.15.0 for d3fc@15.2.11 onwards
