### ISSUE TITLE
Line series points the side of bar series instead of in the middle bar series.

### ISSUE THREAD

**Issue by supriya-somavnshi** [d3fc/d3fc#1800]
Hi,
I am using D3 v6.7 and d3fc v15.2.6 with react . Line series points the side of bar series instead of in the middle of bar. Please suggest me, how to point line series in the mid of bar ??

![image](https://github.com/d3fc/d3fc/assets/73587174/657ad1a9-7b65-47e9-b516-e04f273aa8cf)

I got one solution in d3 .The link has given below :
https://observablehq.com/@d3/bar-line-chart

The following lines do the same work in d3
line = d3.line()
.x(d => x(d.year) + x.bandwidth() / 2)
.y(d => y2(d.efficiency))

But I do not understand how to implement in d3fc .Please suggest me .

I have posted my project on codesandbox.io

https://codesandbox.io/s/youthful-violet-9f745z?file=/src/components/FinancialChart.tsx

**Comment by ColinEberhardt** [comment]
I think the align property of the bar series will do what you want:

https://github.com/d3fc/d3fc/blob/master/packages/d3fc-series/README.md#seriesBar_align

**Comment by ColinEberhardt** [comment]
Checking your code, I can see that you do the following:

~~~
   .align("left")
~~~

This is what is causing the bars to align to the left-hand side of the value. If you remove this line, it will result in the default alignment, which is `middle`.

**Comment by supriya-somavnshi** [comment]
I was able to resolve the issue with your reply. Thank you so much .
