### ISSUE TITLE
d3fc.io examples are not showing

### ISSUE THREAD

**Issue by jhjimenez-lktn** [d3fc/d3fc#1849]
![image](https://github.com/d3fc/d3fc/assets/88005161/3364cfaa-2cd0-40b8-af70-b14c8d2cafc5)

**Comment by jisted-scottlogic** [comment]
Hi, thanks for letting us know. This has helped highlight an issue with the new release process. We're working on it but for now please use version 15.2.6 or earlier.

**Comment by bethpritchard** [comment]
Hi - we had some issues with the build due to migrating to Github Actions. This should now be fixed with d3fc@15.2.12.
