### ISSUE TITLE
https://unpkg.com/d3fc link not found 

### ISSUE THREAD

**Issue by mdmansur1020** [d3fc/d3fc#1850]
Hi 

My frontend application is using d3 and d3fc features with below link as per official documentation says https://github.com/d3fc/d3fc/blob/master/README.md

**<script src="https://unpkg.com/d3"></script>
<script src="https://unpkg.com/d3fc"></script>**

Where d3 available in browser window object but fc not available. 
![image](https://github.com/d3fc/d3fc/assets/12564973/0b9ed3d2-80dd-4ef6-aa68-cd8918cf06d3)

https://unpkg.com/d3fc source says not found. 
![image](https://github.com/d3fc/d3fc/assets/12564973/a6690bf3-be88-4e11-a848-02260d8c5e1d)

Could you please help me with the right d3fc cdn link.

**Comment by bethpritchard** [comment]
Hi - we will try to fix this but for now I'd suggest using an earlier version - https://unpkg.com/d3fc@15.2.6/build/d3fc.js

**Comment by bethpritchard** [comment]
Hi - we had some issues with the build due to migrating to Github Actions. This should now be fixed with d3fc@15.2.12.
