### ISSUE TITLE
Npm install fails for 15 2.11 of d3fc with failed to resolve entry 

### ISSUE THREAD

**Issue by mahendranepali** [d3fc/d3fc#1856]
We use finos perspective which has a d3fc as a dependency.  Npm install fails for 15 2.11 of d3fc with failed to resolve entry

**Comment by DuboisNicolasAirbus** [comment]
Hello,
When I install a d3fc > 15.2.6, the "build" directory is missing in node_modules/d3fc/.
And the package.json specify: "main": "build/d3fc.js"
As workaround, I forced the version to be 15.2.6.

**Comment by bethpritchard** [comment]
Hi - we had some issues with the build due to migrating to Github Actions. This should now be fixed with d3fc@15.2.12.
