### ISSUE TITLE
Components lack transition support

### ISSUE THREAD

**Issue by jleft** [d3fc/d3fc#212]
Currently, the components can be applied to a [selection](https://github.com/mbostock/d3/wiki/Selections), but they don't automatically support [transitions](https://github.com/mbostock/d3/wiki/Transitions) - to animate smoothly between two states. This may be a good feature to add.

[D3's axis component](http://bl.ocks.org/mbostock/1166403) is a nice example of a component which supports transitions.

**Comment by chrisprice** [comment]
* [ ] /indicators/bollingerBands.js
* [ ] /indicators/movingAverage.js
* [ ] /indicators/relativeStrengthIndex.js
* [ ] /scale/gridlines.js
* [ ] /series/bar.js
* [ ] /series/candlestick.js
* [ ] /series/comparison.js
* [ ] /series/line.js
* [ ] /series/ohlc.js
* [ ] /tools/annotation.js
* [ ] /tools/callouts.js
* [ ] /tools/crosshairs.js
* [ ] /tools/fibonacciFan.js
* [ ] /tools/measure.js

**Comment by jleft** [comment]
Most components have a single parameter, [`selection`](https://github.com/ScottLogic/d3-financial-components/blob/f832e51b1f8cbddb2aea0c8dce52740c5a898362/components/series/bar.js#L10), implying the component accepts a selection.

As the transition support is rolled out, components will support a _selection_ or a _transition_. I think _selection_ should be renamed in these components to something more generic.

**Comment by ColinEberhardt** [comment]
Need to add transitions to error bar series #742 

I'd really like to know how we can keep on top of this one. If we get it right my feeling is that this could be a very useful and important part of d3fc..

**Comment by chrisprice** [comment]
This [post](http://bost.ocks.org/mike/path/) covers transitioning lines, although it looks like it'll be hard to make that generalisable.
