### ISSUE TITLE
Add 404 to catch broken links

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#31]
Ensure that all new docs are published to updated URLs and add a 404 which can add a banner to redirected pages indicating the version bump.

**Comment by ColinEberhardt** [comment]
GitHub pages also supports redirects: https://help.github.com/articles/redirects-on-github-pages/

**Comment by chrisprice** [comment]
Looks like the redirect stuff requires jekyll which I don't think we use. Let's just go with the 404 page?
