### ISSUE TITLE
innerDimensions doesn't respect box-sizing

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#406]
We're in good company, jQuery also had [this issue](http://bugs.jquery.com/ticket/11004).

**Comment by ColinEberhardt** [comment]
Can we just use jQuery for this ;-)

**Comment by chrisprice** [comment]
Good plan but we'll need to run it past this guy... https://github.com/ScottLogic/d3-financial-components/commit/67cbe973979ed4e8352d3cc0cfcd2bcd89494d74
