### ISSUE TITLE
Use fc.util.multi within fc.series.stacked...

### ISSUE THREAD

**Issue by janakerman** [d3fc/d3fc#447]
Currently, animations don't work correctly with the current stacked series implementation as we need to add a data join key function (see comment on #442). The stacked series could be improved to support animation by using a `multi` series internally and providing it a `mapping` function that maps each layer of stacked data to the relevant series, harnessing `multi`'s pre-existing animation support.

**Comment by chrisprice** [comment]
N.B. This will only impact *animated* stacked series with *dynamic* groups.

**Comment by chrisprice** [comment]
Don't forget to fix the colouring on the website example.

**Comment by chrisprice** [comment]
Website colouring was previously fixed by a678fd123d4b67b6f086e009bde950a52d042f13
