### ISSUE TITLE
IDEA: Parallel coordinates plot

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#502]
Might be interesting to create one of these plots to see whether any other 'component' ideas fall out:

https://en.wikipedia.org/wiki/Parallel_coordinates

**Comment by ColinEberhardt** [comment]
See the following brushed parallel coordinates plot: https://bl.ocks.org/ColinEberhardt/954400eb99b5fda0b9eb7ef85467bc40

**Comment by chrisprice** [comment]
Duplicate of #1145
