### ISSUE TITLE
Support 'smarter' axis labelling

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#527]
We should consider supporting axis label wrapping:

http://bl.ocks.org/mbostock/7555321

And calculations of the widest axis label

http://stackoverflow.com/questions/17109549/set-y-axis-of-d3-chart-to-fit-widest-label

**Comment by chrisprice** [comment]
Could this feed into the layout stuff?

**Comment by ColinEberhardt** [comment]
Implemented here https://github.com/d3fc/d3fc/tree/master/packages/d3fc-axis#label-rotation--offset
