### ISSUE TITLE
Suggestion: utility to modify zoom behaviour

### ISSUE THREAD

**Issue by CBarrett2** [d3fc/d3fc#531]
Modify zoom behavior so that you can't pan or zoom off the data, or zoom in too far. Also there are potential issues with this and certain series - for example, candlesticks or OHLC series will want to allow some extra space on either side of the far left and right candlestick/ohlc so the whole thing can be viewed, whereas area/point series won't.

https://github.com/ScottLogic/d3fc-showcase/blob/develop/src/assets/js/util/zoomControl.js

**Comment by chrisprice** [comment]
Thanks @CBarrett2, can you make sure all of the links contain the commit hash e.g. -

https://github.com/ScottLogic/d3fc-showcase/blob/e9431b0d09dc60efd9f7b0de8ccc377a60b2497e/src/assets/js/util/zoomControl.js

It just means we don't have to chase through the history if something gets moved, renamed etc..
