### ISSUE TITLE
Support center alignment of axis ticks

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#541]
See this example:

![](http://i.stack.imgur.com/WcmRI.png)

Form the following SO question:

http://stackoverflow.com/questions/17544546/d3-js-align-text-labels-between-ticks-on-the-axis

I originally thought that this could be achieved via decoration, however, having tried, it involves too many calculations that are dependant on scale / ticks etc ...

I think our axes should support tick placement to provide this functionality.

**Comment by chrisprice** [comment]
Could it be wrapped up as a utility you can pass to decorate (accepting the
scale as an argument)?

**Comment by chrisprice** [comment]
#807 is asking for a similar thing for candlesticks. This might lead a bit of weight to implementing this as a utility.

**Comment by ColinEberhardt** [comment]
Fixed in #1245
