### ISSUE TITLE
Add responsive functionality

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#573]
In d3fc-core (as per #572) I'd really like to see some functionality regarding responsive behaviour

**Comment by chrisprice** [comment]
Good idea. I seem to remember stumbling over a library that did something
like this, I'll try and remember what it was...

**Comment by ColinEberhardt** [comment]
Here's the one:

https://gionkunz.github.io/chartist-js/

**Comment by chrisprice** [comment]
![image](https://cloud.githubusercontent.com/assets/433457/10162652/a7dd9b10-66a4-11e5-8ebb-99500be4f420.png)

HOLA!

**Comment by ColinEberhardt** [comment]
Looking at  Mr. Yeoman and Mr. Chartist makes me think d3fc needs a bit more character!

**Comment by timelyportfolio** [comment]
another link with lots of references that might be helpful http://www.sebastianmeier.eu/2015/05/15/responsive-visualizations/

**Comment by ColinEberhardt** [comment]
@timelyportfolio - thanks for the reference, looks like it could be useful.

I think there is a lot of scope for providing novel and quite useful functionality in this area.

**Comment by chrisprice** [comment]
This should now be possible using a combination of -
* `d3fc-element` to associate components of the chart with specific DOM elements
* Responsive CSS to hide the corresponding DOM element when the component is not required 
* Conditional renderering in the `measure`/`redraw` event handlers to only render when the element is visible (maybe using [this trick](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent) `element.offsetParent == null`)

**Comment by ColinEberhardt** [comment]
@chrisprice agreed, I think all the tools are there. Might be good to create a simple demo?

**Comment by chrisprice** [comment]
We should also add some CSS to ensure that the charts on the homepage look good at smaller resolutions (as request in #1077)

**Comment by ColinEberhardt** [comment]
implemented here: https://github.com/d3fc/d3fc/tree/master/packages/d3fc-element#group-autoResize
