### ISSUE TITLE
multi series key function passes (series, index), not (data, index)

### ISSUE THREAD

**Issue by ColinEberhardt** [d3fc/d3fc#574]
I've got an interesting problem, I'm rendering a cartesian chart where the series type is based on some configuration. However, when I switch between series types the previous series is not removed from the SVG. This is because the series is not being rendered via a data-join.

I thought a cunning solution would be to use a multi-series with a key function, adding the series type to the bound data:

```
    // associated the series type with the data
    seriesData.seriesType = seriesType;

    var chart = fc.chart.cartesianChart( ... )

    // the type of series used depends on the seriesType variable
    var series = fc.series.stacked[seriesType]() ...

    var multi = fc.series.multi()
        .key(function(d) { return d.seriesType; })
        .series([series]);

    chart.plotArea(multi);

    container.datum(seriesData)
        .call(chart);
```

However, this does not work because the multi key function is passed (series, index) rather than (data, index):

https://github.com/ScottLogic/d3fc/blob/master/src/series/multi.js#L35

I can't recall why it works that way?

Also, it would be great if there were a less complex way to achieve the same result :-/

**Comment by chrisprice** [comment]
Would this work?

```js
    // associated the series type with the data
    seriesData.seriesType = seriesType;

    var chart = fc.chart.cartesianChart( ... )

    // the type of series used depends on the seriesType variable
    var series = fc.series.stacked[seriesType]() ...

    var multi = fc.series.multi()
        .key(function() { return this.seriesType; })      // <--- HERE
        .series([series]);

    chart.plotArea(multi);

    container.datum(seriesData)
        .call(chart);
```

So `this` is the data, `series` is the first arg and `index` the second. It kind of fits with the idea that the series is what you're using for the data and is the most likely thing to switch on. (Speaking of which, would that work i.e. use `identity` for the `key`?)
