### ISSUE TITLE
Add eslint rule for our module naming convention

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#613]
Enforce an import naming convention of -

``` js
// If there are no naming conflicts, just the imported filename
import dataJoin from '../util/dataJoin';
// To avoid potential naming conflicts, the imported filename suffixed by its containing package name
import dataJoinUtil from '../util/dataJoin';
```

E.g. (N.B. the below links no longer resolve to the intended examples) -
https://github.com/ScottLogic/d3fc/pull/600/files#r41894677
https://github.com/ScottLogic/d3fc/pull/600/files#r41894666

**Comment by ColinEberhardt** [comment]
Good idea

**Comment by bjedrzejewski** [comment]
Shall we add to this issue the rule for the issue that we had with multiSeries / series?

**Comment by chrisprice** [comment]
I think we should create a separate one. The rule for this issue is only going to be applicable to ourselves but I can't see a reason for eslint not to accept the other one as a PR.

**Comment by jdunkerley** [comment]
If we switch on the no-shadow rule then the multiSeries / series rule gets picked up. Comes with a fair few error though.

**Comment by jdunkerley** [comment]
For the naming rule, would we want to accept _dataJoin for the dataJoin for example?

**Comment by chrisprice** [comment]
I agree no-shadow would pick up this case but there is a more general case which I think wouldn't be spotted -

```js
var foo = foo()
```
[jslint](http://www.jslint.com/) spots this with -
> 'foo' is out of scope.

[jshint](http://jshint.com/) does not.

**Comment by bjedrzejewski** [comment]
I am working on this now, using rule: "no-shadow": [2, {"builtinGlobals": true, "hoist": "all"}],

There are about 60 places where it needs fixing, seems to work well.

**Comment by chrisprice** [comment]
@jamesdunkerly no, the rule we came up with says to name the import
importnameInnerpackagename e.g. dataJoinUtil

**Comment by jdunkerley** [comment]
@chrisprice agree hadn't done anything with noShadow. Looked at it and then went off to the playground stuff
