### ISSUE TITLE
Documentation examples do not support resizing

### ISSUE THREAD

**Issue by owennw** [d3fc/d3fc#681]
As shown below, when the browser is narrow the sine graph example overlaps with the side bar.

![d3fc_cartesian](https://cloud.githubusercontent.com/assets/14889759/10730108/b6249e8e-7be5-11e5-8551-5fe45d4c3099.jpg)

**Comment by bjedrzejewski** [comment]
I think this only happens when you start F12 Chrome dev tools or equivalent.

**Comment by chrisprice** [comment]
None of the examples resize, I think that's the cause
