### ISSUE TITLE
Unexpected tick spacing when using discontinuity provider

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#750]
> I created a discontinuityProvider for the foreign exchange market (5 pm Sunday to around 4pm Friday (I just locked it to 4pm to simplify it)). The issue is that the tick spacing becomes unequal when it is applied, even though the chart's data gaps are filled. I looked some at fc.scale.dateTime.tickTransformer, but am not sure where the tick spacing is defined. 
> 
> I assume that there is a date distance metric used for tick spacing, and by closing the gaps I've removed some dates, the result being that the tick that would be placed correctly with gaps is now placed incorrectly.
> 
> Here is an image displaying the problem. The ticks 12pm on Friday and 5pm on Sunday are closer than others (The weekend gap from Friday 4 pm to Sunday 4 pm are removed).  Have you encountered this issue with other discontinuityProviders and do you know of a fix?

![image](https://cloud.githubusercontent.com/assets/433457/11014997/6ee278e4-8544-11e5-82bf-4cf4126f43d4.png)

**Comment by owennw** [comment]
Given the ticks are spaced 12 hours apart what would the expected result be? 

If the discontinuity is not a multiple of 12 hours either there must be an uneven tick spacing, or the ticks move from 00:00/12:00 to other hours after each discontinuity.

**Comment by ColinEberhardt** [comment]
The way the discontinuous date-time axis deals with ticks is pretty simple.

It obtains the ticks from the adapted `d3.time.scale` iterating over the array clamping each of the ticks. The effect of clamping is to ensure that if any ticks falls within a discontinuity it is clamped to the boundary, thus pushing it just outside of the discontinuity.

After clamping any duplicates are removed.

This algorithm does mean that you might see fewer ticks than you would expect. However, d3's approach to ticks is pretty 'fuzzy' in the first place.

Regarding the given example I'm not sure what the expected outcome would be? It looks OK to me - discontinuities always result in funny ticks spacings!

**Comment by chrisprice** [comment]
Closing as expected behaviour
