### ISSUE TITLE
Different behaviour for d3fc.js/d3fc.min.js when using area and line series as keys

### ISSUE THREAD

**Issue by jleft** [d3fc/d3fc#791]
I've been developing a chart which uses multi series (using identity for the key function), area series and line series.

``` js
// Simplified example
var area = fc.series.area();
var line = fc.series.line();

var multi = fc.series.multi()
    .key(fc.util.fn.identity)
    .series([area, line]);
```

This was working fine when I was developing using _d3fc.js_, but when I ran the production build, which uses _d3fc.min.js_, it all went wrong. Either only one of the series would be rendered or a single container would be used by multiple series - which shouldn't be done. Here's a demo:

[d3.js (JS Bin)](https://jsbin.com/mofeyiteli/1/edit?html,js,output)
[d3fc.min.js (JS Bin)](https://jsbin.com/qedobulese/2/edit?html,js,output)

The issue is that the keys (which are ultimately strings) are different in d3fc.js, but the same in d3fc.min.js:
- In d3.js [the strings are different (JS Bin)](https://jsbin.com/quwufilino/2/edit?html,js,output)
- In d3fc.min.js [the strings are the same (JS Bin)](https://jsbin.com/qutitisaju/2/edit?html,js,output)

**Comment by ColinEberhardt** [comment]
Is this an issue? Or just the way d3 works? I vaguely recall that the key for a data join must return a string. If you return something other than a string it still works but with odd behaviour.

**Comment by chrisprice** [comment]
I think this should be documented rather than fixed. Using functions as
keys isn't a pattern I'd want to encourage.

**Comment by jleft** [comment]
It's the way D3 works. `.data()` uses `d3.map` to [map the nodes to keys](https://github.com/mbostock/d3/blob/0d639efa9b78775bef6b1b5c59d6e7da31e85e72/src/selection/data.js#L33-L47). The [map](https://github.com/mbostock/d3/wiki/Arrays#maps) uses [string-coercion for keys](https://github.com/mbostock/d3/blob/5b981a18db32938206b3579248c47205ecc94123/src/arrays/map.js#L54):

> Note: unlike the proposed ES6 map, d3.map still uses string-coercion for keys rather than strict equality.

I agree, I think some documentation explaining how the key function works would be very valuable, and a warning of the potential issues which can arise when keying on functions.
