### ISSUE TITLE
Difficult to access extent of indicator renderers in a way consistent with the series components

### ISSUE THREAD

**Issue by drewmiley** [d3fc/d3fc#806]
Currently the series components expose the `yValue` property, which can be used as an extentAccessor, however the indicator renderers only expose a `root` property, which can not be used in such extent calculations. This makes it surprisingly difficult to calculate the extent of the data on a chart with indicator overlays on. See https://github.com/ScottLogic/d3fc-showcase/pull/454 for how I have attempted to get around this currently- as you can see, adding the extentAccessors manually is not an ideal solution for what I imagine is fairly common desired behaviour.

Could the indicator renderers show these properties so that they can be used in extent calculations? Or could there be a natural modification to `fc.util.extent()` such that a call such as
 `fc.util.extent()
.fields('macd')(data);`
would return what would currently have to be calculated by a much more hard-wired call.
`fc.util.extent()
.fields(['macd', 'signal', 'divergence'])(data.macd);`

**Comment by chrisprice** [comment]
As we've removed the concept of `renderers`, consumers already need to know the names of the fields produced by (what we previously referred to as) the `algorithms`. Therefore I'm not sure this feature request still applies.
