### ISSUE TITLE
donuts and gauge components would be a nice addition

### ISSUE THREAD

**Issue by markjose** [d3fc/d3fc#912]

**Comment by ColinEberhardt** [comment]
D3 itself has very good support for constructing pie / donut charts. Unless we can add some real innovation in this area, it's not something I'd want to prioritise.

For gauges, @oriondean is having a look at implementing a bullet chart - that's probably about as close to a gauge as we would want to get!

**Comment by chrisprice** [comment]
Duplicate of #1085
