### ISSUE TITLE
We aren't testing for correct context in series tests

### ISSUE THREAD

**Issue by alisd23** [d3fc/d3fc#925]
there is a check in the annotation/bandSpec test that the coordinate functions have the correct context - the current element, however these are not tested in the other specs

**Comment by ColinEberhardt** [comment]
Our unit testing is pretty patchy in general! Before adding additional tests we'd probably want to ensure there is some value to them.

**Comment by chrisprice** [comment]
The `annotation/bandSpec` tests were the only thing that picked up we had a massive bug in our implementation. Does that count? :smiley:
