### ISSUE TITLE
d3v4 update

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#944]
| Old | New |
| --- | --- |
| annotation/annotation.js | n.a. |
| annotation/band.js | d3fc-annotation |
| annotation/gridline.js | d3fc-annotation |
| annotation/line.js | d3fc-annotation |
| behavior/behavior.js | n.a. |
| behavior/pointer.js | d3fc-pointer |
| chart/cartesian.js | d3fc-elements (partially) |
| chart/chart.js | n.a. |
| chart/smallMultiples.js | TODO: d3fc-small-multiples |
| chart/sparkline.js | TODO: d3fc-sparkline |
| chart/tooltip.js | deprecated |
| data/data.js | n.a. |
| data/random/filter/skipWeekends.js | d3fc-random-data |
| data/random/financial.js | d3fc-random-data |
| data/random/random.js | n.a. |
| data/random/walk.js | d3fc-random-data |
| data/spread.js | d3fc-group |
| fc.js | n.a. |
| indicator/algorithm/algorithm.js | d3fc-technical-indicator |
| indicator/algorithm/bollingerBands.js | d3fc-technical-indicator |
| indicator/algorithm/elderRay.js | d3fc-technical-indicator |
| indicator/algorithm/envelope.js | d3fc-technical-indicator |
| indicator/algorithm/exponentialMovingAverage.js | d3fc-technical-indicator |
| indicator/algorithm/forceIndex.js | d3fc-technical-indicator |
| indicator/algorithm/macd.js | d3fc-technical-indicator |
| indicator/algorithm/merge.js | [deprecated](https://github.com/d3fc/d3fc-technical-indicator/pull/37/files#diff-f9f6b27e8862175fbd125e7f64b47673R107) |
| indicator/algorithm/movingAverage.js | d3fc-technical-indicator |
| indicator/algorithm/relativeStrengthIndex.js | d3fc-technical-indicator |
| indicator/algorithm/stochasticOscillator.js | d3fc-technical-indicator |
| indicator/indicator.js | n.a. |
| indicator/renderer/bollingerBands.js | d3fc-technical-indicator (example) |
| indicator/renderer/elderRay.js | d3fc-technical-indicator (example) |
| indicator/renderer/envelope.js | d3fc-technical-indicator (example) |
| indicator/renderer/forceIndex.js | d3fc-technical-indicator (example) |
| indicator/renderer/macd.js | d3fc-technical-indicator (example) |
| indicator/renderer/relativeStrengthIndex.js | d3fc-technical-indicator (example) |
| indicator/renderer/renderer.js | n.a. |
| indicator/renderer/stochasticOscillator.js | d3fc-technical-indicator (example) |
| layout/flexbox.js | d3fc-elements (partially) |
| layout/label.js | d3fc-label-layout |
| layout/layout.js | n.a. |
| scale/dateTime.js | d3fc-discontinuous-scale |
| scale/discontinuity/identity.js | d3fc-discontinuous-scale |
| scale/discontinuity/skipWeekends.js | d3fc-discontinuous-scale |
| scale/scale.js | n.a. |
| scale/ticks.js | private |
| series/algorithm/algorithm.js | n.a. |
| series/algorithm/waterfall.js | deprecated |
| series/area.js | d3fc-series |
| series/axis.js | deprecated |
| series/bar.js | d3fc-series |
| series/boxPlot.js | d3fc-series |
| series/candlestick.js | d3fc-series |
| series/cycle.js | deprecated |
| series/errorBar.js | d3fc-series |
| series/grouped.js | d3fc-series |
| series/line.js | d3fc-series |
| series/multi.js | d3fc-series |
| series/ohlc.js | d3fc-series |
| series/ohlcBase.js | internal |
| series/point.js | d3fc-series |
| series/series.js | n.a. |
| series/stacked/area.js | d3fc-series (example) |
| series/stacked/bar.js | d3fc-series (example) |
| series/stacked/line.js | d3fc-series (example) |
| series/stacked/stack.js | d3fc-series (example) |
| series/stacked/stacked.js | n.a. |
| series/waterfall.js | deprecated |
| series/xyBase.js | internal |
| svg/axis.js | d3fc-axis |
| svg/svg.js | n.a. |
| tool/container.js | deprecated |
| tool/crosshair.js | d3fc-annotation |
| tool/tool.js | n.a. |
| util/array.js | internal |
| util/dataJoin.js | d3fc-data-join |
| util/expandRect.js | internal |
| util/extent.js | d3fc-extent |
| util/fn.js | internal |
| util/fractionalBarWidth.js | d3fc-series |
| util/innerDimensions.js | internal |
| util/minimum.js | internal |
| util/percentageChange.js | TODO: move to example somewhere |
| util/render.js | d3fc-elements |
| util/scale.js | internal |
| util/snap.js | deprecated |
| util/util.js | n.a. |

**Comment by WPFerg** [comment]
I'll have a go at `d3fc-sample`, since it's my creation :)

**Comment by ColinEberhardt** [comment]
@WPFerg I'm sure I remember seeing a project which was a d3 path with sampling built-in, might be worth tracking it down for a bit of inspiration.

**Comment by WPFerg** [comment]
I've done a first pass on the `d3fc-sample` component, comments on the commit welcome :)
https://github.com/WPFerg/d3fc-sample/commit/0445777aa17507cf10124ef653e77175781c3fdb

**Comment by ColinEberhardt** [comment]
Thanks @WPFerg - from a quick look through that code it looks really good :-)

With d3fc-label-layout I developed it independently for a while, just pushing changes and trying things out to my own repo. Once it was in a good shape I squashed to a single commit and migrated to the d3fc organization.

How about taking a similar approach? i.e. run with it and we can review when it has fully taken shape

**Comment by WPFerg** [comment]
@ColinEberhardt No problem, I'd squashed a lot of the faff I'd done to set it up, but I'm doing some further refactors to use some higher level functions throughout so I'll do that, but I don't think it'll be too far off of being finished :+1:

**Comment by ColinEberhardt** [comment]
`d3fc-data-join` - I've moved the existing code to a new repo: https://github.com/ColinEberhardt/d3fc-data-join

This gives us a good starting point for any API changes.

**Comment by WPFerg** [comment]
`d3fc-sample` transferred to the `d3fc` group

**Comment by tlsim** [comment]
Here's a first pass at d3fc-feed: https://github.com/tlsim/d3fc-feed/commit/851d61b668efa56a9db0ec753e9311107a4f85fd

**Comment by ColinEberhardt** [comment]
Thanks @tlsim `d3fc-feed` looks really good to me. I've added a few minor comments on that commit.

**Comment by tlsim** [comment]
Thanks @ColinEberhardt - it's updated here: https://github.com/tlsim/d3fc-financial-feed/commit/ffee40966952417ecb404fd9c6d580f8c7d1ebe7 Let me know if it looks ready to move over and release.

**Comment by ColinEberhardt** [comment]
That looks spot on to me @tlsim - I'd be happy to see that moved over.

**Comment by tlsim** [comment]
https://github.com/tlsim/d3fc-indicator/commit/84b1f487094564597951b0fe4bd955c076c384d5 is ready for review.

**Comment by ColinEberhardt** [comment]
Thanks @tlsim - looks like  good first-cut to me, just a few minor comments.

I think there is quite a lot more that could be done to improve `d3fc-indicator`, but this is a good starting point.

**Comment by tlsim** [comment]
https://github.com/tlsim/d3fc-random-data/commit/7d2db316031317f7b7e3eedab0b0ef7ab316f2f7 ready for initial review.

**Comment by jleft** [comment]
Just curious... Is there a reason why `d3fc-rebind`'s methods aren't exposed in d3fc?

**Comment by ColinEberhardt** [comment]
Thanks @tlsim - I'll take a look shortly.

**Comment by ColinEberhardt** [comment]
Looks good to me @tlsim - a few comments, mostly about the GBM code. As mentioned in the comments, might be worth removing this, resulting in a financial-specific component, `d3fc-random-financial-data` perhaps?

**Comment by ColinEberhardt** [comment]
> Just curious... Is there a reason why d3fc-rebind's methods aren't exposed in d3fc?

I can't see any obvious reason - no.

**Comment by ColinEberhardt** [comment]
We seem to have quite a bit of variability in how our `d3fc-*` projects are configured. When creating a new package I pick one, then modify it, which means the variability just spreads! We have projects with different dependencies (some un-necessary), different ways of configuring jasmine, etc ...

Having just created a new project, I thought I'd copy the configuration into a separate repo, which we can then use to ensure we all use the same seed:

https://github.com/ColinEberhardt/d3fc-package-archetype

Thoughts?

**Comment by ColinEberhardt** [comment]
@chrisprice - currently we are using a different module name for each of our packages:

https://github.com/d3fc/d3fc-shape/blob/master/rollup.config.js#L5

However, D3v4 uses the module name `d3` throughout. Adopting this pattern would make using the code, via globals, a bit less verbose. For example `fc_discontinuous_scale.discontinuousScale` becomes `fc.discontinuousScale`

**Comment by ColinEberhardt** [comment]
And here's another one ...

https://github.com/d3fc/d3fc-discontinuous-scale

I'd appreciate some review feedback before I do a v1.0 release. Also, I'm not so keen on the name. Anyone got some more succinct ideas?!

**Comment by chrisprice** [comment]
I really like the underlying idea of the archetype but I'm not sure it goes quite far enough. As well as providing the boilerplate you really want to be able to do up-to-date checks, almost like a linting tool for projects.

**Comment by ColinEberhardt** [comment]
@chrisprice I've kick-started series:

https://github.com/ColinEberhardt/d3fc-series

A few notes on migration:

- API has been changed to expose 'context' allowing SVG rendering
- Following the D3v4 direction, the series now has very basic styling without the need for CSS
- Test suite is slightly more comprehensive that d3fc, focussing on functionality rather than implementation detail.
- More detailed usage instructions in README
