### ISSUE TITLE
Mobile view of website

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#99]
A few things that jump out -

* [x] There's no sub-section navigation within API or Examples
* [x] The example charts aren't very responsive. Whilst they do render smaller, there's too many ticks and legends etc. overflow.
* [x] The github/codepen buttons are wrapping in an ugly way. Maybe the text should be removed at low resolutions?
* [x] Code blocks are wrapping rather than overflowing which makes them very hard to read.

**Comment by mbssantos** [comment]
picking up item 2, fixing mobile chart examples
