### ISSUE TITLE
Split tools into behaviours and renderers

### ISSUE THREAD

**Issue by chrisprice** [d3fc/d3fc#999]
There are a number of issues (#841, #821, #645) that relate to the inflexibility/simplicity of the crosshairs implementation and the tight binding between events and rendering. A pragmatic way forward would seem to be to split the tools into behaviours (e.g. `select` consisting of `enter`/`move`/`leave`) and renderers (e.g. crosshair), then encourage flux-type event handling.

**Comment by rhewitt** [comment]
Nice idea! I like to display data in a label above the chart. Haven't yet looked at doing that in D3FC. Separating rendering from events should certainly make things like that easier. If the renderer's supplied as a function, and could optionally be a user-provided renderer, that would be really nice.

**Comment by chrisprice** [comment]
This has now been done as part of the upgrade to D3 version 4. Crosshair has now been split into d3fc/d3fc-annotation (renderer) and d3fc/d3fc-pointer (event). The rest of the tools will be migrated as and when we need them. PRs welcome :smiley:
